{
 "title": "Fedex",
 "time": { "from": "2023-01-31T07:17:29.101Z", "to": "2023-01-31T07:23:54.025Z" },
 "panels": [
  {
   "title": "histogram message process time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(roadrunner_message_process_time_seconds_bucket[1h])) by (le, tenant,zone,hostname))"
    },
    {}
   ]
  },
  {
   "title": "websocket read & ack time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(websocket_read_time_ms_sum[4m])) by (hostname, tenant, zone) / sum(rate(websocket_read_time_ms_count[4m])) by (hostname, tenant, zone)"
    },
    {
     "expr": "sum(rate(websocket_ack_time_ms_sum[4m])) by (connectorId, hostname, tenant, zone) / sum(rate(websocket_ack_time_ms_count[4m])) by (connectorId, hostname, tenant, zone)"
    }
   ]
  },
  {
   "title": "message_process_time_seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(roadrunner_message_process_time_seconds_sum[4m])) by (tenant,zone,hostname) / sum(rate(roadrunner_message_process_time_seconds_count[4m])) by (tenant,zone,hostname)"
    }
   ]
  },
  {
   "title": "file processing time seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(file_processing_time_seconds_sum[4m])) by (hostname, tenant, zone) / sum(rate(file_processing_time_seconds_count[4m])) by (hostname, tenant, zone)"
    }
   ]
  },
  {
   "title": "producer chan send time ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(producer_chan_send_time_ms_sum[4m])) by (tenant, producer_index, zone) / sum(rate(producer_chan_send_time_ms_count[4m])) by (tenant, producer_index, zone)"
    }
   ]
  },
  {
   "title": "kafka bytes count ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(fedex_kafka_producer_bytes_count[4m])) by (topic)",
     "legendFormat": "kafka producer bytes count"
    },
    {}
   ]
  },
  {
   "title": "roadrunner mo's",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "targets": [
    { "expr": "rate(roadrunner_mo_count[15m])" }
   ]
  },
  {
   "title": "roadrunner_sensor_agent_connections",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "roadrunner_sensor_agent_connections"
    }
   ]
  }
 ]
}