kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "grafana.fullname" . }}-config
data:
    GF_SERVER_ROOT_URL: "https://{{ .Values.global.analytics.deployment.name }}.{{ .Values.global.analytics.deployment.domain }}/grafana"
    GF_SERVER_DOMAIN: "{{ .Values.global.analytics.deployment.name }}.{{ .Values.global.analytics.deployment.domain }}"
    GF_AUTH_ANONYMOUS_ENABLED: "true"
    GF_AUTH_ANONYMOUS_ORG_ROLE: "Admin"
    GF_LOG_LEVEL: "{{ .Values.grafana.env.LOG_LEVEL }}"
