apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  name: grafana-exporter
  labels:
    app: grafana-exporter
spec:
  selector:
    matchLabels:
      app: grafana-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana-exporter
    spec:
      imagePullSecrets: {{ toYaml .Values.global.images.pullSecrets | nindent 14 }}
    {{- if eq .Values.global.deployment_type "dev" }}
      nodeSelector:
        size: dev-pool
      tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: devpool
    {{- end }}    
      containers:
      - name: grafana-exporter
        image: {{ .Values.grafana_exporter.image.registry }}/{{ .Values.grafana_exporter.image.repository }}:{{ .Values.grafana_exporter.image.tag }}
        imagePullPolicy: {{ .Values.grafana_exporter.image.pullPolicy }}
        resources:
          {{- toYaml .Values.grafana_exporter.resources | nindent 12 }}
        ports:
        - containerPort: 8080
        command: ["/opt/grafana-impex/exporter-webserver"]
      restartPolicy: Always



