apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    grafana_datasource: "true"
  name: prometheus-datasource
data:
  prometheus-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
      basicAuth: false
      isDefault: true
      version: 1
      editable: true