# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2.1

commands:
  exportsecret:
    steps:
      - run:
          name: "Export secrets from vault and create context"
          command: |
            # export all secret
            export $(grep -v '^#' /tmp/.envvault | xargs)
            export_secrets() {

              while read -r line; do
                key=$(echo $line | cut -d: -f1 | xargs)
                value=$(echo $line | cut -d: -f2 | xargs)

                echo "Parsed key-value pair: $key=$value"
                echo "export $key=\"$value\"" >> $BASH_ENV

              done
            }

            vault login --no-print -method=github token=${GITHUB_TOKEN}
            vault kv get -format=yaml -field=data -mount=kv besbuilder | export_secrets

# Jobs
jobs:
  thebuild:
    machine: true
    resource_class: accedian/staging_bes-ubuntu-medium

    working_directory: /root/go/src/github.com/accedian/grafana-docker

    steps:
      - checkout
      - exportsecret
      - run:
          name: Building Docker Container
          command: make build

  release:
    machine: true
    resource_class: accedian/staging_bes-ubuntu-medium

    working_directory: /root/go/src/github.com/accedian/grafana-docker
    steps:
      - checkout 
      - exportsecret
      - run:
          name: "Push image to GCR"
          command: |
            # Only push docker image when on master branch on the Accedian project
            if [ "${CIRCLE_BRANCH}" == "master" ] && [ "${CIRCLE_PROJECT_USERNAME}" == "Accedian" ]; then
               echo $GCLOUD_SERVICE_KEY | base64 -d  > ${HOME}/gcloud-service-key.json
               docker login -u _json_key -p "$(echo $GCR_DOCKER_RW_PASSWORD | base64 -d)" https://gcr.io
               echo "Now Tagging"
               git config --global user.email "${CIRCLE_USERNAME}@accedian.com"
               git config --global user.name "CircleCI"
               git semver minor
               export IMAGE_TAG=$(git semver get)
               git push origin master ${IMAGE_TAG}
               make push
            fi

workflows:
  version: 2
  build_and_release:
    jobs:
      - thebuild:
          context: bes-builder-gcp-skybuilder-prd-51843

      - release:
          context: bes-builder-gcp-skybuilder-prd-51843
          requires:
            - thebuild
          filters:
            branches:
              only: master       
