version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          if [ -n "$GRAFANA_VERSION" ]; then
            ./build.sh "$GRAFANA_VERSION"
            docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
            ./push_to_docker_hub.sh "$GRAFANA_VERSION"

            if echo "$GRAFANA_VERSION" | grep -q "^master-"; then
              apk add --no-cache curl
              ./deploy_to_k8s.sh "grafana/grafana-dev:$GRAFANA_VERSION"
            fi
          fi
