{
 "title": "Airflow",
 "description": "Phase 1 dashboard",
 "tags": [ "airflow" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "dagId", "label": "Dag Id", "query": "label_values(dag_id)" },
   { "name": "status", "label": "Task Status", "query": "label_values(status)" }
  ]
 },
 "panels": [
  {
   "title": "Dag Run Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(airflow_dag_run_duration{dag_id =~ '$dagId'}[5m])) by (dag_id)\n",
     "legendFormat": "{{dag_id}}"
    }
   ]
  },
  {
   "title": "Dag Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(airflow_dag_status{dag_id =~ '$dagId'}[10s])) by (dag_id, status)\n",
     "legendFormat": "{{dag_id}}-{{status}}"
    }
   ]
  },
  {
   "title": "Task Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(airflow_task_status{dag_id =~ '$dagId', status =~ '$status'}[10s])) by (dag_id, task_id, status)\n",
     "legendFormat": "{{dag_id}}-{{task_id}}-{{status}}"
    }
   ]
  }
 ]
}