{
 "title": "Alert Service Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Alert Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(alert_service_errors_total[$__rate_interval])) + sum(increase(alert_service_mqtt_errors_total[$__rate_interval])))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Consumed Alerts (Kafka)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(alert_service_consumed_kafka_mgs_total[$__rate_interval]))",
     "legendFormat": "Kafka Ingestion"
    }
   ]
  },
  {
   "title": "Session Alerts rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(alert_service_session_mgs_total[$__rate_interval])) + sum(increase(alert_service_micro_tca_mgs_total[$__rate_interval]))",
     "legendFormat": "Kafka Ingestion"
    }
   ]
  },
  {
   "title": "Capture Alerts rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(alert_service_capture_mgs_total[$__rate_interval])) + sum(increase(alert_service_capture_automatic_mgs_total[$__rate_interval]))",
     "legendFormat": "Kafka Ingestion"
    }
   ]
  },
  {
   "title": "Average API Calls Duration in the last 5 min",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(alert_service_rest_api_call_duration_seconds_sum[5m])) by (endpoint)) / (sum(rate(alert_service_rest_api_call_duration_seconds_count[5m])) by (endpoint))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "MQTT Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(alert_service_mqtt_errors_total[$__rate_interval]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Published Alerts (MQTT)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(alert_service_produced_mqtt_mgs_total[$__rate_interval]))",
     "legendFormat": "Kafka Ingestion"
    }
   ]
  },
  {
   "title": "NetSec Alerts rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(alert_service_netsec_mgs_total[$__rate_interval]))",
     "legendFormat": "Kafka Ingestion"
    }
   ]
  },
  {
   "title": "Anomaly Msgs rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(alert_service_anomaly_mgs_total[$__rate_interval]))",
     "legendFormat": "Kafka Ingestion"
    }
   ]
  },
  {
   "title": "Active Alert Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(increase(alert_service_active_alert_errors_total[$__rate_interval]))",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Consumed/Published Divergence",
   "type": "stat",
   "description": "Shows if the Kafka output and the MQTT output are diverging. If they are, then this can be a sign that alert service is not able to keep up with the amount of data Kafka is outputting.",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "abs(sum(increase(alert_service_consumed_kafka_mgs_total[$__rate_interval])) - sum(increase(alert_service_produced_mqtt_mgs_total[$__rate_interval])))",
     "legendFormat": "Kafka In : MQTT Out"
    }
   ]
  },
  {
   "title": "Average API Calls Duration in the last 5 min",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(sum(increase(alert_service_rest_api_call_duration_seconds_sum[5m])) by (endpoint)) / (sum(increase(alert_service_rest_api_call_duration_seconds_count[5m])) by (endpoint))",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Alert Service Instances Up Status",
   "type": "timeseries",
   "description": "Drops means that alert service was not running",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "up{job=\"alert-service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active Alerts overtime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(alert_service_current_active_alerts)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Alert Errors",
   "type": "graph",
   "description": "There should not be any errors in the alerting workflow. If there are errors, we at least have a rough timestamp to check alert service logs.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(alert_service_errors_total[$__rate_interval])) + sum(increase(alert_service_mqtt_errors_total[$__rate_interval]))",
     "legendFormat": "Total Alert Errors"
    },
    {
     "expr": "sum(increase(alert_service_mqtt_errors_total[$__rate_interval]))",
     "legendFormat": "MQTT Errors"
    },
    {
     "expr": "sum(increase(alert_service_active_alert_errors_total[$__rate_interval]))",
     "legendFormat": "Active alert errors"
    }
   ]
  },
  {
   "title": "Alerts increase within time (by type)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(alert_service_session_mgs_total[$__rate_interval])) + sum(increase(alert_service_micro_tca_mgs_total[$__rate_interval]))",
     "legendFormat": "session"
    },
    {
     "expr": "sum(increase(alert_service_capture_mgs_total[$__rate_interval])) + sum(increase(alert_service_capture_automatic_mgs_total[$__rate_interval]))",
     "legendFormat": "capture"
    },
    {
     "expr": "sum(increase(alert_service_anomaly_mgs_total[$__rate_interval]))",
     "legendFormat": "anomaly"
    },
    {
     "expr": "sum(increase(alert_service_netsec_mgs_total[$__rate_interval]))",
     "legendFormat": "network security"
    }
   ]
  },
  {
   "title": "Raised vs Cleared Alerts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(increase(alert_service_cleared_alert_total[$__rate_interval]))",
     "legendFormat": "Cleared"
    },
    {
     "expr": "sum(increase(alert_service_active_alert_total[$__rate_interval]))",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Consumed/Published Divergence",
   "type": "graph",
   "description": "This chart will tell you if the Kafka output and the MQTT output are diverging. If they are, then this can be a sign that alert service is not able to keep up with the amount of data Kafka is outputting.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "abs(increase(alert_service_consumed_kafka_mgs_total[$__rate_interval]) - increase(alert_service_produced_mqtt_mgs_total[$__rate_interval]))",
     "legendFormat": "Divergence"
    }
   ]
  },
  {
   "title": "Consumed vs Published",
   "type": "graph",
   "description": "This is a graph to show the pattern of MQTT and Kafka. They should ideally be identical and if they diverge, it means alert service is unable to keep up.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(alert_service_consumed_kafka_mgs_total[$__rate_interval]))",
     "legendFormat": "Consumed (Kafka)"
    },
    {
     "expr": "sum(increase(alert_service_produced_mqtt_mgs_total[$__rate_interval]))",
     "legendFormat": "Published (MQTT)"
    }
   ]
  },
  {
   "title": "Published MQTT messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "rate(alert_service_produced_mqtt_mgs_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MQTT errors while publishing messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "rate(alert_service_mqtt_errors_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}