{
 "title": "Alert Policies",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "tenantId",
    "label": "Tenant ID",
    "query": {
     "query": "label_values(gather_alert_policies_counter_by_tenant,tenantId)"
    }
   },
   {
    "name": "policyType",
    "label": "Policy Type",
    "query": {
     "query": "label_values(gather_enabled_alert_policies_by_tenant,policyType)"
    }
   },
   {
    "name": "errorType",
    "label": "ErrorType",
    "query": {
     "query": "label_values(gather_alert_policy_operation_failure,errorType)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Alert Policies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Enabled",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gather_alert_policies_counter_by_tenant{tenantId=\"$tenantId\", enabled=\"true\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deleted",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gather_alert_policies_counter_by_tenant{tenantId=\"$tenantId\", deleted=\"true\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Archived",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gather_alert_policies_counter_by_tenant{tenantId=\"$tenantId\", enabled=\"false\", deleted=\"true\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Micro TCA",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gather_alert_policies_counter_by_tenant{tenantId=\"$tenantId\", \"policyType\"=\"micro-tca\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Capture",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gather_alert_policies_counter_by_tenant{tenantId=\"$tenantId\", policyType=\"capture\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Security",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gather_alert_policies_counter_by_tenant{tenantId=\"$tenantId\", policyType=\"security\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Limits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Enabled (Micro TCA)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 14 },
   "repeat": "policyType",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gather_enabled_alert_policies_by_tenant{policyType=\"micro-tca\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Enabled (Capture)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 14 },
   "repeat": "policyType",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gather_enabled_alert_policies_by_tenant{policyType=\"capture\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Enabled (Security)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 14 },
   "repeat": "policyType",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gather_enabled_alert_policies_by_tenant{policyType=\"security\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max (Micro TCA)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 20 },
   "repeat": "policyType",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gather_max_number_of_alert_policies_by_tenant{policyType=\"micro-tca\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max (Capture)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 20 },
   "repeat": "policyType",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gather_max_number_of_alert_policies_by_tenant{policyType=\"capture\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max (Security)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 20 },
   "repeat": "policyType",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gather_max_number_of_alert_policies_by_tenant{policyType=\"security\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Operations results", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Operation: Create (error)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gather_alert_policy_operation_failure{tenantId=\"$tenantId\", operation=\"create\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operation: Update (error)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gather_alert_policy_operation_failure{tenantId=\"$tenantId\", operation=\"update\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Operation: Delete (error)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gather_alert_policy_operation_failure{tenantId=\"$tenantId\", operation=\"delete\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error per type: $errorType",
   "type": "stat",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gather_alert_policy_operation_failure{tenantId=\"$tenantId\", errorType=\"$errorType\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}