{
 "title": "Alerts",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Alert Errors per min",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(gather_metric_alerts_service_active_errors_since_startup[1m]) + rate(gather_metric_alerts_service_mqtt_errors_since_startup[1m]) + rate(gather_metric_alerts_service_errors_since_startup[1m])",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Alert Errors",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    { "expr": "rate(spark_alerts_errors[1m])", "legendFormat": "Alert Errors" }
   ]
  },
  {
   "title": "Active Session Policies",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "spark_alerts_active_policies{job=\"Spark-Alerting-Metric-Publisher\"}"
    }
   ]
  },
  {
   "title": "Input Output Lag per min",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "abs(rate(gather_metric_alerts_service_consumed_kafka_mgs_since_startup[1m]) - rate(gather_metric_alerts_service_produced_mqtt_mgs_since_startup[1m]))",
     "legendFormat": "Kafka In : MQTT Out"
    }
   ]
  },
  {
   "title": "MQTT Messages per min",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rate(gather_metric_alerts_service_produced_mqtt_mgs_since_startup[1m])",
     "legendFormat": "Kafka Ingestion"
    }
   ]
  },
  {
   "title": "Session Msgs per min",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rate(gather_metric_alerts_service_session_mgs_since_startup[1m])",
     "legendFormat": "Kafka Ingestion"
    }
   ]
  },
  {
   "title": "NetSec Msgs per min",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 11, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rate(gather_metric_alerts_service_netsec_mgs_since_startup[1m])",
     "legendFormat": "Kafka Ingestion"
    }
   ]
  },
  {
   "title": "Kafka ingestion per min",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rate(gather_metric_alerts_service_consumed_kafka_mgs_since_startup[1m])",
     "legendFormat": "Kafka Ingestion"
    }
   ]
  },
  {
   "title": "Capture Msgs per min",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 17, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rate(gather_metric_alerts_service_capture_mgs_since_startup[1m])",
     "legendFormat": "Kafka Ingestion"
    }
   ]
  },
  {
   "title": "Anomaly Msgs per min",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 20, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "rate(gather_metric_alerts_service_anonmaly_mgs_since_startup[1m])",
     "legendFormat": "Kafka Ingestion"
    }
   ]
  },
  {
   "title": "Gather Alert msg type per min",
   "type": "graph",
   "gridPos": { "h": 13, "w": 13, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(gather_metric_alerts_service_session_mgs_since_startup[1m])",
     "legendFormat": "session"
    },
    {
     "expr": "rate(gather_metric_alerts_service_capture_mgs_since_startup[1m])",
     "legendFormat": "capture"
    },
    {
     "expr": "rate(gather_metric_alerts_service_anomaly_mgs_since_startup[1m])",
     "legendFormat": "anomaly"
    },
    {
     "expr": "rate(gather_metric_alerts_service_netsec_mgs_since_startup[1m])",
     "legendFormat": "network security"
    }
   ]
  },
  {
   "title": "Gather Input/Output Metrics (stacked)",
   "type": "graph",
   "description": "This is a graph to show the pattern of MQTT and Kafka. They should ideally be identical and if they diverge, it means gather is unable to keep up.",
   "gridPos": { "h": 13, "w": 11, "x": 13, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(gather_metric_alerts_service_consumed_kafka_mgs_since_startup[1m])",
     "legendFormat": "Kafka msgs"
    },
    {
     "expr": "rate(gather_metric_alerts_service_produced_mqtt_mgs_since_startup[1m])",
     "legendFormat": "MQTT msgs"
    }
   ]
  },
  {
   "title": "Gather  Active/Clear per min",
   "type": "graph",
   "gridPos": { "h": 13, "w": 13, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(gather_metric_alerts_service_cleared_since_startup[1m])",
     "legendFormat": "Cleared"
    },
    {
     "expr": "rate(gather_metric_alerts_service_active_alerts_since_startup[1m])",
     "legendFormat": "Active"
    }
   ]
  },
  {
   "title": "Gather Alert Message Types Counts Since startup",
   "type": "graph",
   "description": "Type of alerts going through the system since gather startup. Not useful as is. Maybe more useful as a pie chart",
   "gridPos": { "h": 13, "w": 11, "x": 13, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gather_metric_alerts_service_session_mgs_since_startup",
     "legendFormat": "session"
    },
    {
     "expr": "gather_metric_alerts_service_capture_mgs_since_startup",
     "legendFormat": "catpure"
    },
    {
     "expr": "gather_metric_alerts_service_netsec_mgs_since_startup",
     "legendFormat": "netsec"
    },
    {
     "expr": "gather_metric_alerts_service_anomaly_mgs_since_startup",
     "legendFormat": "anomaly"
    }
   ]
  },
  {
   "title": "Gather Alert Checkpointing rate",
   "type": "graph",
   "description": "Alert's require checkpointing every hour. This is to track the rate of checkpoints",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(gather_metric_alerts_service_checkpointed_since_startup[1m])",
     "legendFormat": "Checkpoints"
    }
   ]
  },
  {
   "title": "Gather Kafka MQTT Divergence",
   "type": "graph",
   "description": "This chart will tell you if the Kafka output and the MQTT output are diverging. If they are, then this can be a sign that Gather is not able to keep up with the amount of data Kafka is outputting.",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "abs(rate(gather_metric_alerts_service_consumed_kafka_mgs_since_startup[1m]) - rate(gather_metric_alerts_service_produced_mqtt_mgs_since_startup[1m]))",
     "legendFormat": "Kafka - MQTT"
    }
   ]
  },
  {
   "title": "Spark Alerts by Tenant",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (tenant) (spark_alerts_raised)",
     "legendFormat": "{{tenant}} Raised Alerts"
    },
    {
     "expr": "sum by (tenant) (spark_alerts_cleared)",
     "legendFormat": "{{tenant}} Cleared Alerts"
    }
   ]
  },
  {
   "title": "Spark Alerts by Policy",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(policyId) (spark_alerts_raised)",
     "legendFormat": "{{policyId}} Raised Alerts"
    },
    {
     "expr": "sum by (policyId) (spark_alerts_cleared)",
     "legendFormat": "{{policyId}} Cleared Alerts"
    }
   ]
  },
  {
   "title": "Spark Alerts Produced Rate by tenant:PolicyID",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (policyId, tenant) (\n  rate(spark_alerts_produced[1m])\n)\n",
     "legendFormat": "{{tenant}}::{{policyId}} Alert Produced"
    }
   ]
  },
  {
   "title": "Spark Alerts Records Analyzed Per minute",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(spark_alerts_records_consumed{job=\"Spark-Alerting-Metric-Publisher\"}[1m])",
     "legendFormat": "{{tenant}}::{{policyId}} Produced Alerts"
    }
   ]
  },
  {
   "title": "Gather Alert Parsing Errors",
   "type": "graph",
   "description": "There should not be any errors in the alerting workflow. If there are errors, we at least have a rough timestamp to check gather's logs.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gather_metric_alerts_service_errors_since_startup",
     "legendFormat": "Alert Errors"
    },
    {
     "expr": "gather_metric_alerts_service_mqtt_errors_since_startup",
     "legendFormat": "MQTT Errors"
    },
    {
     "expr": "gather_metric_alerts_service_active_errors_since_startup",
     "legendFormat": "Active Errors"
    }
   ]
  },
  {
   "title": "Spark Alert Parsing Errors",
   "type": "graph",
   "description": "There should not be any errors in the alerting workflow. If there are errors, we at least have a rough timestamp to check gather's logs.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_alert_errors  ",
     "legendFormat": "{{tenant}}::{{policyId}} Alert Errors"
    }
   ]
  }
 ]
}