{
 "title": "Analytics-Streamer API",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "General metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Kafka Message Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(analytics_streamer_gNMI_info_total_kafka_msg_processed{container=\"analytics-streamer-api\"}[1m])",
     "legendFormat": "Messages Processsed"
    }
   ]
  },
  {
   "title": "Active consumers",
   "type": "bargauge",
   "gridPos": { "h": 19, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "analytics_streamer_gNMI_info_active_kafka_consumers{container=\"analytics-streamer-api\"}",
     "legendFormat": "{{topic_partition}}"
    }
   ]
  },
  {
   "title": "Max Kafka Message Throughput",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "rate(analytics_streamer_gNMI_info_total_kafka_msg_processed{container=\"analytics-streamer-api\"}[1m])",
     "legendFormat": "Messages Processsed"
    }
   ]
  },
  {
   "title": "Stage Processing Time",
   "type": "gauge",
   "description": "Gauge to monitor time per stage in pipeline",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(analytics_streamer_gNMI_stage_processing_time_ns_sum{component=\"KafkaConsumer\"}[1m]))\n/  \nsum(rate(analytics_streamer_gNMI_stage_processing_time_ns_count{component=\"KafkaConsumer\"}[1m]))",
     "legendFormat": "Kafka Consumer"
    },
    {
     "expr": "sum(rate(analytics_streamer_gNMI_stage_queue_time_ns_sum{component=\"KafkaConsumer->YangProcessor\"}[1m]))\n/  \nsum(rate(analytics_streamer_gNMI_stage_queue_time_ns_count{component=\"KafkaConsumer->YangProcessor\"}[1m]))",
     "legendFormat": "Kafka -> Yang Queue"
    },
    {
     "expr": "sum(rate(analytics_streamer_gNMI_stage_processing_time_ns_sum{component=\"YangProcessor\"}[1m]))\n/  \nsum(rate(analytics_streamer_gNMI_stage_processing_time_ns_count{component=\"YangProcessor\"}[1m]))",
     "legendFormat": "Yang Processor"
    },
    {
     "expr": "sum(rate(analytics_streamer_gNMI_stage_queue_time_ns_sum{component=\"YangProcessor->gNMI_Server\"}[1m]))\n/  \nsum(rate(analytics_streamer_gNMI_stage_queue_time_ns_count{component=\"YangProcessor->gNMI_Server\"}[1m]))",
     "legendFormat": "Yang -> gNMI Server Queue"
    },
    {
     "expr": "sum(rate(analytics_streamer_gNMI_stage_processing_time_ns_sum{component=\"gNMI_Server\"}[1m]))\n/  \nsum(rate(analytics_streamer_gNMI_stage_processing_time_ns_count{component=\"gNMI_Server\"}[1m]))",
     "legendFormat": "gNMI Server"
    },
    {
     "expr": "sum(rate(analytics_streamer_gNMI_stage_processing_time_ns_sum{component=\"gNMI_Client\"}[1m]))\n/  \nsum(rate(analytics_streamer_gNMI_stage_processing_time_ns_count{component=\"gNMI_Client\"}[1m]))",
     "legendFormat": "gNMI Server -> Client Delivery"
    },
    {
     "expr": "sum(rate(analytics_streamer_gNMI_stage_processing_time_ns_sum{component=\"AnalyticsStreamer\"}[1m]))\n/  \nsum(rate(analytics_streamer_gNMI_stage_processing_time_ns_count{component=\"AnalyticsStreamer\"}[1m]))",
     "legendFormat": "Analytics Streamer Total"
    }
   ]
  },
  {
   "title": "Total Kafka Messages Processed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "analytics_streamer_gNMI_info_total_kafka_msg_processed",
     "legendFormat": "{{job}}:{{tenantId}}"
    }
   ]
  },
  { "title": "Ingestion lag", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Ingestion Lag across partitions",
   "type": "timeseries",
   "description": "Shows how many messages are waiting to be processed",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "analytics_streamer_gNMI_ingestion_lag",
     "legendFormat": "{{topic_partition}}"
    }
   ]
  },
  {
   "title": "Maximum Ingestion Lag over time",
   "type": "timeseries",
   "description": "Shows how many messages are waiting to be processed",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(analytics_streamer_gNMI_ingestion_lag)",
     "legendFormat": "Maximum ingestion lag"
    }
   ]
  },
  {
   "title": "Maximum Ingestion Lag",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "max(analytics_streamer_gNMI_ingestion_lag)",
     "legendFormat": "Maximum ingestion lag"
    }
   ]
  },
  { "title": "Failures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } }
 ]
}