{
 "title": "Analytics-Streamer gNMI",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Application State",
   "type": "bargauge",
   "description": "Panel to show insight into what the current state of the streamer is",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (analytics_streamer_gNMI_info_active_tenant_streams)",
     "legendFormat": "Active gNMI Streams"
    },
    {
     "expr": "sum (analytics_streamer_gNMI_info_active_tenant_subscriptions)",
     "legendFormat": "Active Subscriptions"
    },
    {
     "expr": "sum (analytics_streamer_gNMI_info_active_kafka_consumers)",
     "legendFormat": "Active Kafka Consumers"
    }
   ]
  },
  {
   "title": "Active Monitored Objects Subscribed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "analytics_streamer_gNMI_info_active_tenant_monitored_objects",
     "legendFormat": "{{job}}:{{tenantId}}"
    }
   ]
  },
  {
   "title": "Stage Processing Time",
   "type": "bargauge",
   "description": "Gauge to monitor time per stage in pipeline",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(analytics_streamer_gNMI_stage_processing_time_ns_sum{component=\"KafkaConsumer\"}[1m]))\n/  \nsum(rate(analytics_streamer_gNMI_stage_processing_time_ns_count{component=\"KafkaConsumer\"}[1m]))",
     "legendFormat": "Kafka Consumer"
    },
    {
     "expr": "sum(rate(analytics_streamer_gNMI_stage_queue_time_ns_sum{component=\"KafkaConsumer->YangProcessor\"}[1m]))\n/  \nsum(rate(analytics_streamer_gNMI_stage_queue_time_ns_count{component=\"KafkaConsumer->YangProcessor\"}[1m]))",
     "legendFormat": "Kafka -> Yang Queue"
    },
    {
     "expr": "sum(rate(analytics_streamer_gNMI_stage_processing_time_ns_sum{component=\"YangProcessor\"}[1m]))\n/  \nsum(rate(analytics_streamer_gNMI_stage_processing_time_ns_count{component=\"YangProcessor\"}[1m]))",
     "legendFormat": "Yang Processor"
    },
    {
     "expr": "sum(rate(analytics_streamer_gNMI_stage_queue_time_ns_sum{component=\"YangProcessor->gNMI_Server\"}[1m]))\n/  \nsum(rate(analytics_streamer_gNMI_stage_queue_time_ns_count{component=\"YangProcessor->gNMI_Server\"}[1m]))",
     "legendFormat": "Yang -> gNMI Server Queue"
    },
    {
     "expr": "sum(rate(analytics_streamer_gNMI_stage_processing_time_ns_sum{component=\"gNMI_Server\"}[1m]))\n/  \nsum(rate(analytics_streamer_gNMI_stage_processing_time_ns_count{component=\"gNMI_Server\"}[1m]))",
     "legendFormat": "gNMI Server"
    },
    {
     "expr": "sum(rate(analytics_streamer_gNMI_stage_processing_time_ns_sum{component=\"gNMI_Client\"}[1m]))\n/  \nsum(rate(analytics_streamer_gNMI_stage_processing_time_ns_count{component=\"gNMI_Client\"}[1m]))",
     "legendFormat": "gNMI Server -> Client Delivery"
    },
    {
     "expr": "sum(rate(analytics_streamer_gNMI_stage_processing_time_ns_sum{component=\"AnalyticsStreamer\"}[1m]))\n/  \nsum(rate(analytics_streamer_gNMI_stage_processing_time_ns_count{component=\"AnalyticsStreamer\"}[1m]))",
     "legendFormat": "Analytics Streamer Total"
    }
   ]
  },
  {
   "title": "Stage Messages Processed",
   "type": "graph",
   "description": "Rate of messages processed",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(analytics_streamer_gNMI_info_total_kafka_msg_processed[1m])",
     "legendFormat": "{{job}}:Kafka"
    },
    {
     "expr": "rate(analytics_streamer_gNMI_info_total_yang_msg_processed[1m])",
     "legendFormat": "{{job}}:Yang"
    },
    {
     "expr": "rate(analytics_streamer_gNMI_info_total_gnmi_msg_processed[1m])",
     "legendFormat": "{{job}}:gNNI_server"
    }
   ]
  },
  {
   "title": "Ingestion Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "analytics_streamer_gNMI_ingestion_lag",
     "legendFormat": "{{job}}:{{topic_partition}}"
    }
   ]
  },
  {
   "title": "Metrics Delivery Time",
   "type": "graph",
   "description": "Time in seconds from metric creation to streaming out to a client",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "analytics_streamer_gNMI_ingestion_metrics_stream_time_s_sum / analytics_streamer_gNMI_ingestion_metrics_stream_time_s_count",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_swarm_service_name=~\"aod_analytics-streamer.*\"}",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}.{{container_label_com_docker_swarm_service_id}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(container_cpu_user_seconds_total{container_label_com_docker_swarm_service_name=~\"aod_analytics-streamer.*\"}[5m]) * 100",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}.{{container_label_com_docker_swarm_service_id}}"
    }
   ]
  },
  {
   "title": "Subscription Attempt Failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (cause)(analytics_streamer_gNMI_server_subscription_failure)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection Failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (system) (analytics_streamer_gNMI_info_communication_failure)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Yang Unpopulated Required Fields",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (field) (analytics_streamer_gNMI_yang_data_missing)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka Parse Failures",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (field) (analytics_streamer_gNMI_kafka_data_mapping)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}