{
 "title": "Capture sensors",
 "description": "Catpure sensor monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "tenant_id",
    "label": "Tenant",
    "query": {
     "query": "label_values(collectd_uptime{}, tenant_id)"
    }
   },
   {
    "name": "capture_id",
    "label": "Capture IDs",
    "query": {
     "query": "label_values(collectd_uptime{tenant_id=\"$tenant_id\"}, capture_id)"
    }
   },
   {
    "name": "actual_disks",
    "label": "actual_disks",
    "query": {
     "query": "label_values(collectd_iostat_gauge{tenant_id=\"$tenant_id\",capture_id=\"$capture_id\"}, iostat)"
    }
   },
   {
    "name": "nif",
    "label": "nif",
    "query": {
     "query": "label_values(collectd_interface_if_octets_rx_total{tenant_id=\"$tenant_id\",capture_id=\"$capture_id\"}, interface)"
    }
   },
   {
    "name": "process_name",
    "label": "Process name",
    "query": {
     "query": "label_values(collectd_processes_ps_vm{tenant_id=\"$tenant_id\",capture_id=\"$capture_id\"}, processes)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Processor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "timeseries",
   "description": "Capture sensors uptime",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "collectd_uptime{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\"}",
     "legendFormat": "{{capture_id}} uptime"
    }
   ]
  },
  {
   "title": "System Load",
   "type": "timeseries",
   "description": "Capture sensor system load",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_replace({__name__=~\"collectd_load_.*term\",job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\"}, \"term\", \"$1\", \"__name__\", \"collectd_load_(.*)term\")",
     "legendFormat": "{{capture_id}} {{term}}"
    }
   ]
  },
  {
   "title": "CPUs average (jiffies)",
   "type": "timeseries",
   "description": "Capture sensor CPUs average",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without (cpu,exported_instance, instance, job, monitor, tenant_id)(irate(collectd_cpu_total{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\"}[5m]))  \n/ ignoring(type) group_left \n  sum without (cpu, type,exported_instance, instance, job, monitor, tenant_id)(irate(collectd_cpu_total{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\"}[5m])) ",
     "legendFormat": "{{capture_id}} - {{type}}"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "description": "Capture sensor memory usage in Bytes (IEC i.e. in power of 1024)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "collectd_memory{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\"}",
     "legendFormat": "{{capture_id}} - {{memory}}"
    }
   ]
  },
  {
   "title": "Swap usage",
   "type": "timeseries",
   "description": "Capture sensor swap usage in Bytes (IEC i.e. in power of 1024)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "collectd_swap{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\"}",
     "legendFormat": "{{capture_id}} - {{swap}}"
    }
   ]
  },
  { "title": "Disk Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Filesystem root usage",
   "type": "timeseries",
   "description": "Capture sensor filesystem root usage in Bytes  (IEC i.e. in power of 1024)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "collectd_df_df_complex{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",df=\"root\"}",
     "legendFormat": "{{capture_id}} - {{df}} - {{type}}"
    }
   ]
  },
  {
   "title": "Filesystem srv usage",
   "type": "timeseries",
   "description": "Capture sensor filesystem root usage in Bytes  (IEC i.e. in power of 1024)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "collectd_df_df_complex{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",df=\"srv\"}",
     "legendFormat": "{{capture_id}} - {{df}} - {{type}}"
    }
   ]
  },
  {
   "title": "Disk / (persistence)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Operation duration (ms)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "irate(collectd_disk_disk_time_read_total{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",disk=~\"sd[a|b]4\"}[5m])",
       "legendFormat": "{{disk}} read"
      },
      {
       "expr": "irate(collectd_disk_disk_time_write_total{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",disk=~\"sd[a|b]4\"}[5m]) * -1",
       "legendFormat": "{{disk}} write"
      }
     ]
    },
    {
     "title": "Transfert (B/s)",
     "type": "timeseries",
     "description": "Disk data transfer in Bytes per seconds (IEC i.e. in power of 1024)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "irate(collectd_disk_disk_octets_read_total{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",disk=~\"sd[a|b]4\"}[5m])",
       "legendFormat": "{{disk}} read"
      },
      {
       "expr": "irate(collectd_disk_disk_octets_write_total{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",disk=~\"sd[a|b]4\"}[5m]) * -1",
       "legendFormat": "{{disk}} write"
      }
     ]
    },
    {
     "title": "Merged operation",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "irate(collectd_disk_disk_merged_read_total{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",disk=~\"sd[a|b]4\"}[5m])",
       "legendFormat": "{{disk}} read"
      },
      {
       "expr": "irate(collectd_disk_disk_merged_write_total{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",disk=~\"sd[a|b]4\"}[5m]) * -1",
       "legendFormat": "{{disk}} write"
      }
     ]
    },
    {
     "title": "Operation/s",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "irate(collectd_disk_disk_ops_read_total{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",disk=~\"sd[a|b]4\"}[5m])",
       "legendFormat": "{{disk}} read"
      },
      {
       "expr": "irate(collectd_disk_disk_ops_write_total{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",disk=~\"sd[a|b]4\"}[5m]) * -1",
       "legendFormat": "{{disk}} write"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk /srv (monodisk)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Operation duration (ms)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "irate(collectd_disk_disk_time_read_total{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",disk=~\"sd[a|b]5\"}[5m])",
       "legendFormat": "{{disk}} read"
      },
      {
       "expr": "irate(collectd_disk_disk_time_write_total{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",disk=~\"sd[a|b]5\"}[5m]) * -1",
       "legendFormat": "{{disk}} write"
      }
     ]
    },
    {
     "title": "Transfert (B/s)",
     "type": "timeseries",
     "description": "Disk data transfer in Bytes per seconds (IEC i.e. in power of 1024)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "irate(collectd_disk_disk_octets_read_total{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",disk=~\"sd[a|b]5\"}[5m])",
       "legendFormat": "{{disk}} read"
      },
      {
       "expr": "irate(collectd_disk_disk_octets_write_total{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",disk=~\"sd[a|b]5\"}[5m]) * -1",
       "legendFormat": "{{disk}} write"
      }
     ]
    },
    {
     "title": "Merged operation",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "irate(collectd_disk_disk_merged_read_total{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",disk=~\"sd[a|b]5\"}[5m])",
       "legendFormat": "{{disk}} read"
      },
      {
       "expr": "irate(collectd_disk_disk_merged_write_total{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",disk=~\"sd[a|b]5\"}[5m]) * -1",
       "legendFormat": "{{disk}} write"
      }
     ]
    },
    {
     "title": "Operation/s",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "irate(collectd_disk_disk_ops_read_total{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",disk=~\"sd[a|b]5\"}[5m])",
       "legendFormat": "{{disk}} read"
      },
      {
       "expr": "irate(collectd_disk_disk_ops_write_total{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",disk=~\"sd[a|b]5\"}[5m]) * -1",
       "legendFormat": "{{disk}} write"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk /srv (multidisk)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Operation duration (ms)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "irate(collectd_disk_disk_time_read_total{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",disk=~\"sd[a|b]1\"}[5m])",
       "legendFormat": "{{disk}} read"
      },
      {
       "expr": "irate(collectd_disk_disk_time_write_total{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",disk=~\"sd[a|b]1\"}[5m]) * -1",
       "legendFormat": "{{disk}} write"
      }
     ]
    },
    {
     "title": "Transfert (B/s)",
     "type": "timeseries",
     "description": "Disk data transfer in Bytes per seconds (IEC i.e. in power of 1024)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "irate(collectd_disk_disk_octets_read_total{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",disk=~\"sd[a|b]1\"}[5m])",
       "legendFormat": "{{disk}} read"
      },
      {
       "expr": "irate(collectd_disk_disk_octets_write_total{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",disk=~\"sd[a|b]1\"}[5m]) * -1",
       "legendFormat": "{{disk}} write"
      }
     ]
    },
    {
     "title": "Merged operation",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "irate(collectd_disk_disk_merged_read_total{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",disk=~\"sd[a|b]1\"}[5m])",
       "legendFormat": "{{disk}} read"
      },
      {
       "expr": "irate(collectd_disk_disk_merged_write_total{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",disk=~\"sd[a|b]1\"}[5m]) * -1",
       "legendFormat": "{{disk}} write"
      }
     ]
    },
    {
     "title": "Operation/s",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "irate(collectd_disk_disk_ops_read_total{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",disk=~\"sd[a|b]1\"}[5m])",
       "legendFormat": "{{disk}} read"
      },
      {
       "expr": "irate(collectd_disk_disk_ops_write_total{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",disk=~\"sd[a|b]1\"}[5m]) * -1",
       "legendFormat": "{{disk}} write"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk IO stats [[actual_disks]]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "repeat": "actual_disks",
   "collapsed": true,
   "panels": [
    {
     "title": "Merged requests queued to [[actual_disks]] per second",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "collectd_iostat_gauge{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",iostat=~\"$actual_disks\", type=\"rrqm_s\"}",
       "legendFormat": "{{iostat}} read (rrqm/s)"
      },
      {
       "expr": "collectd_iostat_gauge{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",iostat=~\"$actual_disks\", type=\"wrqm_s\"}",
       "legendFormat": "{{iostat}} write (wrqm/s)"
      }
     ]
    },
    {
     "title": "Number of requests (after merge) on [[actual_disks]]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "expr": "collectd_iostat_gauge{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",iostat=~\"$actual_disks\", type=\"r_s\"}",
       "legendFormat": "{{iostat}} read (r/s)"
      },
      {
       "expr": "collectd_iostat_gauge{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",iostat=~\"$actual_disks\", type=\"w_s\"}",
       "legendFormat": "{{iostat}} write (w/s)"
      }
     ]
    },
    {
     "title": "Throughput on [[actual_disks]] (MB/s)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "MiBs" } },
     "targets": [
      {
       "expr": "collectd_iostat_gauge{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",iostat=~\"$actual_disks\", type=\"rMB_s\"}",
       "legendFormat": "{{iostat}} read (rMB/s)"
      },
      {
       "expr": "collectd_iostat_gauge{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",iostat=~\"$actual_disks\", type=\"wMB_s\"}",
       "legendFormat": "{{iostat}} write (wMB/s)"
      }
     ]
    },
    {
     "title": "Average request size on [[actual_disks]] (kilobytes)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "kbytes" } },
     "targets": [
      {
       "expr": "collectd_iostat_gauge{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",iostat=~\"$actual_disks\", type=\"rareq-sz\"}",
       "legendFormat": "{{iostat}} read (rareq-sz)"
      },
      {
       "expr": "collectd_iostat_gauge{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",iostat=~\"$actual_disks\", type=\"wareq-sz\"}",
       "legendFormat": "{{iostat}} write (wareq-sz)"
      }
     ]
    },
    {
     "title": "Average request wait time (queue time + service time) on [[actual_disks]] (ms)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "collectd_iostat_gauge{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",iostat=~\"$actual_disks\", type=\"r_await\"}",
       "legendFormat": "{{iostat}} read (r_await)"
      },
      {
       "expr": "collectd_iostat_gauge{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",iostat=~\"$actual_disks\", type=\"w_await\"}",
       "legendFormat": "{{iostat}} write (w_await)"
      }
     ]
    },
    {
     "title": "Average request queue length on [[actual_disks]]",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "collectd_iostat_gauge{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",iostat=~\"$actual_disks\", type=\"aqu-sz\"}",
       "legendFormat": "{{iostat}} queue length (aqu-sz)"
      }
     ]
    },
    {
     "title": "[[actual_disks]] utilization (%)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "collectd_iostat_gauge{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",iostat=~\"$actual_disks\", type=\"%util\"}",
       "legendFormat": "{{iostat}} utilization (%util)"
      }
     ]
    }
   ]
  },
  {
   "title": "Network interface [[nif]]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "repeat": "nif",
   "collapsed": true,
   "panels": [
    {
     "title": "Traffic (B/s)",
     "type": "timeseries",
     "description": "Network data traffic in Bytes per seconds (IEC i.e. in power of 1024)",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "irate(collectd_interface_if_octets_rx_total{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",interface=~\"$nif\"}[5m])",
       "legendFormat": "{{interface}} rx"
      },
      {
       "expr": "irate(collectd_interface_if_octets_tx_total{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",interface=~\"$nif\"}[5m]) * -1",
       "legendFormat": "{{interface}} tx"
      }
     ]
    },
    {
     "title": "Packets",
     "type": "timeseries",
     "description": "Network data traffic in packets per seconds",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(collectd_interface_if_packets_rx_total{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",interface=~\"$nif\"}[5m])",
       "legendFormat": "{{interface}} rx"
      },
      {
       "expr": "irate(collectd_interface_if_packets_tx_total{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",interface=~\"$nif\"}[5m]) * -1",
       "legendFormat": "{{interface}} tx"
      }
     ]
    },
    {
     "title": "Errors",
     "type": "timeseries",
     "description": "Network interfaces errors per second",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "irate(collectd_interface_if_errors_rx_total{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",interface=~\"$nif\"}[5m])",
       "legendFormat": "{{interface}} rx"
      },
      {
       "expr": "irate(collectd_interface_if_errors_tx_total{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",interface=~\"$nif\"}[5m]) * -1",
       "legendFormat": "{{interface}} tx"
      }
     ]
    }
   ]
  },
  {
   "title": "Process [[process_name]]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "repeat": "process_name",
   "collapsed": true,
   "panels": [
    {
     "title": "[[process_name]] memory usage",
     "type": "timeseries",
     "description": "Process memory usage in Bytes (IEC i.e. in power of 1024)",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "label_replace({__name__=~\"collectd_processes_ps_(vm|data|rss)\",job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",processes=~\"$process_name\"}, \"ps_type\", \"$1\", \"__name__\", \"collectd_processes_ps_(.*)\")",
       "legendFormat": "{{capture_id}} - {{ps_type}}"
      }
     ]
    },
    {
     "title": "[[process_name]]  processes and threads",
     "type": "timeseries",
     "description": "Number of processes and threads",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "label_replace({__name__=~\"collectd_processes_ps_count_(processes|threads)\",job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",processes=~\"$process_name\"}, \"ps_type\", \"$1\", \"__name__\", \"collectd_processes_ps_count_(.*)\")",
       "legendFormat": "{{capture_id}} - {{ps_type}}"
      }
     ]
    },
    {
     "title": "[[process_name]]  CPU time (%)",
     "type": "timeseries",
     "description": "Process CPU time usage in percentage",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(collectd_processes_ps_cputime_syst_total{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",processes=~\"$process_name\"}[5m]) * 0.0001",
       "legendFormat": "{{capture_id}} - syst"
      },
      {
       "expr": "irate(collectd_processes_ps_cputime_user_total{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",processes=~\"$process_name\"}[5m]) * 0.0001",
       "legendFormat": "{{capture_id}} - user"
      }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "expr": "collectd_temperature_gauge{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\"}",
       "legendFormat": "{{capture_id}} - {{temperature}} - {{type}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Junkie internal stats - interfaces",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Junkie stats - interfaces drops",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(collectd_junkie_gauge{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",junkie=~\"iface-eth.+\",type=~\".*_drop.*\"}[5m])",
       "legendFormat": "{{junkie}} / {{type}}"
      }
     ]
    },
    {
     "title": "Junkie stats - interfaces bytes received",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "irate(collectd_junkie_gauge{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",junkie=~\"iface-eth.+\",type=\"tot_bytes\"}[5m])",
       "legendFormat": "{{junkie}} / {{type}}"
      }
     ]
    },
    {
     "title": "Junkie stats - interfaces duplicates",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(collectd_junkie_gauge{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",junkie=~\"iface-eth.+\",type=\"tot_duplicate\"}[5m])",
       "legendFormat": "{{junkie}} / {{type}}"
      }
     ]
    },
    {
     "title": "Junkie stats - interfaces received packets",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(collectd_junkie_gauge{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",junkie=~\"iface-eth.+\",type=\"tot_packets\"}[5m])",
       "legendFormat": "{{junkie}} / {{type}}"
      }
     ]
    },
    {
     "title": "Junkie stats - interfaces total received packets",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "irate(collectd_junkie_gauge{job=\"collectd\",monitor=\"capture\",tenant_id=\"$tenant_id\",capture_id=~\"$capture_id\",junkie=~\"iface-eth.+\",type=\"tot_received\"}[5m])",
       "legendFormat": "{{junkie}} / {{type}}"
      }
     ]
    }
   ]
  }
 ]
}