{
 "title": "Clickhouse",
 "description": "Clickhouse metrics",
 "tags": [
  "clickhouse",
  "db"
 ],
 "time": { "from": "now/d", "to": "now" },
 "panels": [
  {
   "title": "Query",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseMetrics_Query[1m])"
    }
   ]
  },
  {
   "title": "Merge",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ClickHouseMetrics_Merge", "legendFormat": "merge {{job}}" },
    {
     "expr": "rate(ClickHouseProfileEvents_MergedRows[1m])",
     "legendFormat": "rate {{job}}"
    }
   ]
  },
  {
   "title": "Replication",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_ReplicatedChecks"
    },
    {
     "expr": "ClickHouseMetrics_ReplicatedFetch"
    },
    {
     "expr": "ClickHouseMetrics_ReplicatedSend"
    }
   ]
  },
  {
   "title": "ReadOnly replica",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 2, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(ClickHouseMetrics_ReadonlyReplica)"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_LeaderReplica",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Compressed Read Buffer",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_CompressedReadBufferBytes[1m])",
     "legendFormat": "{{job}}"
    },
    {}
   ]
  },
  {
   "title": "Read/Write",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ClickHouseMetrics_Read" },
    { "expr": "ClickHouseMetrics_Write" }
   ]
  },
  {
   "title": "Pool Tasks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_BackgroundPoolTask",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_TCPConnection",
     "legendFormat": "tcp {{instance}}"
    },
    {
     "expr": "ClickHouseMetrics_HTTPConnection",
     "legendFormat": "http {{instance}}"
    },
    {
     "expr": "ClickHouseMetrics_InterserverConnection",
     "legendFormat": "interserver"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_MemoryTracking"
    }
   ]
  },
  {
   "title": "Cache rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_MarkCacheMisses[5m])",
     "legendFormat": "misses {{job}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_MarkCacheHits[5m])",
     "legendFormat": "hits {{job}}"
    }
   ]
  }
 ]
}