{
 "title": "CybersecuritySparkApp",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Time since the last batch was completed successfully",
   "type": "graph",
   "gridPos": { "h": 7, "w": 19, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(time() * 1000 - spark_CustomMetricSource_detection_completionTimestamp) / 1000",
     "legendFormat": "{{detection}}"
    }
   ]
  },
  {
   "title": "Failed Detections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "increase(spark_CustomMetricSource_detection_failedJobsTotal{job=\"cyberapp\"}[2m])",
     "legendFormat": "failed detections count"
    }
   ]
  },
  {
   "title": "Top 10 triggered alerts in a timeframe",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sort_desc(ceil(increase(spark_CustomMetricSource_alerts_count_total{job=\"cyberapp\"}[$__range]))))",
     "legendFormat": "{{detection}}"
    },
    {}
   ]
  },
  {
   "title": "Generate alert latency, ms",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_CustomMetricSource_alerts_creation_millis{job=\"cyberapp\", quantile=\"0.95\"}",
     "legendFormat": "{{detection}}"
    }
   ]
  },
  {
   "title": "Batch Processing Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Processing lag",
   "type": "graph",
   "description": "Count of Kafka messages not yet consumed",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=~\"cybersecurity.cyberapp.[a-z0-9]{8}-.+\",instance=\"kafka-topic-metric-exporter:9308\",job=\"kafka-topic-metrics\", topic=~\"pvx.*\"})",
     "legendFormat": "processing lag"
    }
   ]
  },
  {
   "title": "Batch processing duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "spark_CustomMetricSource_batch_processingTimeMs{job=\"cyberapp\"}"
    }
   ]
  },
  {
   "title": "Spark batch start delay",
   "type": "graph",
   "description": "Time taken for the first job of this batch to start processing from the time this batch was submitted to the streaming scheduler.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "time() - spark_CustomMetricSource_batch_timestamp{job=\"cyberapp\", role=\"driver\"} / 1000",
     "legendFormat": "batch timestamp"
    }
   ]
  },
  {
   "title": "Number of records in a batch",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_CustomMetricSource_batch_numRecords{job=\"cyberapp\"}"
    }
   ]
  },
  {
   "title": "Processing rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short", "label": "records/sec" }
   ],
   "targets": [
    {
     "expr": "spark_CustomMetricSource_batch_processingRate{job=\"cyberapp\"}",
     "legendFormat": "processingRate"
    },
    {
     "expr": "spark_CustomMetricSource_batch_inputRate{job=\"cyberapp\"}",
     "legendFormat": "inputRate"
    }
   ]
  },
  {
   "title": "Dynamic Resource Allocation: Executors",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "spark_CustomMetricSource_da_executors{job=\"cyberapp\"}",
     "legendFormat": "num executors"
    }
   ]
  },
  {
   "title": "Dynamic Resource Allocation: ratio",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "avg_over_time(spark_CustomMetricSource_batch_inputRate{job=\"cyberapp\"}[6m])/avg_over_time(spark_CustomMetricSource_batch_processingRate{job=\"cyberapp\"}[6m])",
     "legendFormat": "approx scaling ratio"
    }
   ]
  },
  {
   "title": "Detection Jobs Execution Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "title": "By detection executor run time",
   "type": "graph",
   "description": "Time the spark executor spends actually running the detection tasks (including fetching shuffle data).",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(spark_CustomMetricSource_detection_task_executorRunTime{job=\"cyberapp\"}) by (detection,stage)",
     "legendFormat": "{{detection}} [stage {{stage}}]"
    }
   ]
  },
  {
   "title": "Detection deserialize time",
   "type": "graph",
   "description": "Time taken on the spark executor to deserialize detection task.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(spark_CustomMetricSource_detection_task_executorDeserializeTime{job=\"cyberapp\"}) by (detection, stage)",
     "legendFormat": "{{detection}} [stage {{stage}}]"
    }
   ]
  },
  {
   "title": "Input records",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(spark_CustomMetricSource_detection_input_recordsRead{stage=\"0\"}) by (detection)",
     "legendFormat": "{{detection}}"
    }
   ]
  },
  {
   "title": "Shuffle Read Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(spark_CustomMetricSource_detection_shuffleread_totalBytesRead{job=\"cyberapp\"}) by (detection,stage)",
     "legendFormat": "total {{detection}} [{{stage}}]"
    },
    {
     "expr": "sum(spark_CustomMetricSource_detection_shuffleread_remoteBytesRead{job=\"cyberapp\"}) by (detection,stage)",
     "legendFormat": "remote {{detection}} [{{stage}}]"
    },
    {
     "expr": "sum(spark_CustomMetricSource_detection_shuffleread_localBytesRead) by (detection,stage)",
     "legendFormat": "local {{detection}} [{{stage}}]"
    }
   ]
  },
  {
   "title": "Shuffle Write Stats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(spark_CustomMetricSource_detection_shufflewrite_bytesWritten) by (detection, stage)",
     "legendFormat": "written bytes {{detection}} [{{stage}}]"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(spark_JVMCPU_jvmCpuTime{job=\"cyberapp\", role=\"executor\"}[60s])/10000000000",
       "legendFormat": "executor cpuTime %"
      }
     ]
    },
    {
     "title": "Heap",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "spark_ExecutorMetrics_JVMHeapMemory{job=\"cyberapp\", role=\"executor\"} / 1024 / 1024",
       "legendFormat": "JVM heap memory used, Mb"
      },
      {
       "expr": "spark_ExecutorMetrics_OnHeapStorageMemory{job=\"cyberapp\",role=\"executor\"}/1024/1024"
      }
     ]
    },
    {
     "title": "GC time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(spark_ExecutorMetrics_MinorGCTime{job=\"cyberapp\", role=\"executor\"}[1m])",
       "legendFormat": "minor GC time"
      },
      {
       "expr": "rate(spark_ExecutorMetrics_MajorGCTime{job=\"cyberapp\", role=\"executor\"}[1m])",
       "legendFormat": "major GC time"
      }
     ]
    },
    {
     "title": "GC count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(spark_ExecutorMetrics_MinorGCCount{job=\"cyberapp\",role=\"executor\"}[1m])",
       "legendFormat": "minor GC count"
      },
      {
       "expr": "increase(spark_ExecutorMetrics_MajorGCCount{job=\"cyberapp\",role=\"executor\"}[1m])",
       "legendFormat": "MajorGC"
      }
     ]
    },
    {
     "title": "Connection check",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(connectivity_check{job=\"pinger\"}-clamp_max(floor((time() - push_time_seconds{job=\"pinger\"}) / 300), 1)) by(service)",
       "legendFormat": "conn[ {{service}} ]"
      }
     ]
    }
   ]
  },
  {
   "title": "Redis State Store",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "READ latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(spark_CustomMetricSource_statestore_readLatency{job=\"cyberapp\"}[1m])/1000",
       "legendFormat": "{{detection}} "
      },
      {
       "expr": "sum(increase(spark_CustomMetricSource_statestore_readLatency{job=\"cyberapp\"}[1m]))/1000",
       "legendFormat": "total latency (across all partitions)"
      }
     ]
    },
    {
     "title": "WRITE latency",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(spark_CustomMetricSource_statestore_writeLatency{job=\"cyberapp\"}[1m])/1000",
       "legendFormat": "{{detection}}"
      },
      {
       "expr": "sum(increase(spark_CustomMetricSource_statestore_writeLatency{job=\"cyberapp\"}[1m]))/1000",
       "legendFormat": "total latency (across partitions)"
      }
     ]
    },
    {
     "title": "Total states read from Redis",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(spark_CustomMetricSource_statestore_reads{job=\"cyberapp\"}[1m])",
       "legendFormat": "{{detection}}"
      }
     ]
    },
    {
     "title": "Total states written to Redis",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(spark_CustomMetricSource_statestore_writes{job=\"cyberapp\"}[1m])",
       "legendFormat": "{{detection}}"
      }
     ]
    },
    {
     "title": "Total serialization duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(spark_CustomMetricSource_statestore_serializeLatency{job=\"cyberapp\"}[1m])",
       "legendFormat": "{{detection}}"
      }
     ]
    },
    {
     "title": "Total deserialization duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(spark_CustomMetricSource_statestore_deserializeLatency{job=\"cyberapp\"}[1m])",
       "legendFormat": "{{detection}}"
      }
     ]
    },
    {
     "title": "Number of states evicted from Redis",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "spark_CustomMetricSource_statestore_evictedCount{job=\"cyberapp\"}",
       "legendFormat": "{{detection}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Other",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "REST client latency",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "spark_CustomMetricSource_rest_latency_millis{job=\"cyberapp\", quantile=\"0.95\"}",
       "legendFormat": "{{client}}: {{route}}"
      }
     ]
    },
    {
     "title": "REST errors count",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(spark_CustomMetricSource_rest_errors_total{job=\"cyberapp\", quantile=\"0.95\"}[1m]) or vector(0)",
       "legendFormat": "{{client}}: {{route}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DSL Feed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last synced (minutes ago)",
     "type": "stat",
     "gridPos": { "h": 6, "w": 7, "x": 0, "y": 45 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(time() - max_over_time(dslfeed_lastSynchronized[24h])/ 1000) / 60",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Sync errors over the past hour",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 7, "x": 7, "y": 45 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(dslfeed_errors_total[1h])",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}