{
 "title": "Druid",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": "label_values(jvm_info, cluster)"
   },
   {
    "name": "druid_datasource",
    "label": "druid datasource",
    "query": "label_values(druid_broker_query_time_ms_sum{cluster=\"$cluster\"}, datasource)"
   }
  ]
 },
 "panels": [
  {
   "title": "Broker Query Count Per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "druid_historical_query_success_count"
    },
    {
     "expr": "druid_broker_query_success_count"
    },
    {
     "expr": "druid_broker_query_failed_count"
    },
    {
     "expr": "druid_historical_query_failed_count"
    },
    {
     "expr": "druid_broker_query_interrupted_count"
    },
    {
     "expr": "druid_historical_query_interrupted_count"
    }
   ]
  },
  { "title": "JMX Heap Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Heap Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "jvm_memory_bytes_max", "legendFormat": "{{instance}} {{area}}" }
   ]
  },
  {
   "title": "Heap Usage Delta",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "delta(jvm_memory_bytes_max[5m])",
     "legendFormat": "{{instance}} {{area}}"
    }
   ]
  },
  {
   "title": "Broker metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache hits rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(druid_broker_query_cache_hits_count{instance=~\"druid.*:8000\"}[5m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Cache misses rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(druid_broker_query_cache_misses_count{instance=~\"druid.*:8000\"}[5m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Cache timeouts/errors rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(druid_broker_query_cache_timeouts_count{instance=~\"druid.*:8000\"}[5m])",
       "legendFormat": "timeouts {{ instance }}"
      },
      {
       "expr": "rate(druid_broker_query_cache_errors_count{instance=~\"druid.*:8000\"}[5m])",
       "legendFormat": "errors {{ instance }}"
      }
     ]
    },
    {
     "title": "Cached objects",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "druid_broker_query_cache_numentries_count{instance=~\"druid.*:8000\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Cache size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "druid_broker_query_cache_size_bytes{instance=~\"druid.*:8000\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Cache evictions rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(druid_broker_query_cache_evictions_count{instance=~\"druid.*:8000\"}[5m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Query response time - p50",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(druid_broker_query_time_ms_bucket{datasource=~\"$druid_datasource\"}[5m])) by (le, datasource))",
       "legendFormat": "{{ datasource }}"
      }
     ]
    },
    {
     "title": "Query response time - p75",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 36 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.75, sum(rate(druid_broker_query_time_ms_bucket{instance=~\"druid.*:8000\", datasource=~\"$druid_datasource\"}[5m])) by (le, datasource))",
       "legendFormat": "{{ datasource }}"
      }
     ]
    },
    {
     "title": "Query response time - p90",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 36 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(rate(druid_broker_query_time_ms_bucket{instance=~\"druid.*:8000\", datasource=~\"$druid_datasource\"}[5m])) by (le, datasource))",
       "legendFormat": "{{ datasource }}"
      }
     ]
    },
    {
     "title": "Query count (per second)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(idelta(druid_broker_query_time_ms_count{datasource=~\"$druid_datasource\"}[5m])) by (datasource)",
       "legendFormat": "{{ datasource }}"
      }
     ]
    },
    {
     "title": "Query response size - p50",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 50 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(druid_broker_query_bytes_bucket{datasource=~\"$druid_datasource\"}[5m])) by (le, datasource))",
       "legendFormat": "{{ datasource }}"
      }
     ]
    },
    {
     "title": "Query response size - p75",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 50 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.75, sum(rate(druid_broker_query_bytes_bucket{instance=~\"druid.*:8000\", datasource=~\"$druid_datasource\"}[5m])) by (le, datasource))",
       "legendFormat": "{{ datasource }}"
      }
     ]
    },
    {
     "title": "Query response size - p90",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 50 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(rate(druid_broker_query_bytes_bucket{datasource=~\"$druid_datasource\"}[5m])) by (le, datasource))",
       "legendFormat": "{{ datasource }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Historical metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cache hits rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(druid_historical_query_cache_hits_count{instance=~\"druid.*:8000\"}[5m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Cache misses rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(druid_historical_query_cache_misses_count{instance=~\"druid.*:8000\"}[5m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Cache evictions rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(druid_historical_query_cache_evictions_count{instance=~\"druid.*:8000\"}[5m])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Cached objects",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "druid_historical_query_cache_numentries_count{instance=~\"druid.*:8000\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Cache size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "druid_historical_query_cache_size_bytes{instance=~\"druid.*:8000\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Cache timeouts/errors rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(druid_historical_query_cache_timeouts_count{instance=~\"druid.*:8000\"}[5m])",
       "legendFormat": "timeouts {{ instance }}"
      },
      {
       "expr": "rate(druid_historical_query_cache_errors_count{instance=~\"druid.*:8000\"}[5m])",
       "legendFormat": "errors {{ instance }}"
      }
     ]
    },
    {
     "title": "Query response time - p50",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 41 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(druid_historical_query_time_ms_bucket{datasource=~\"$druid_datasource\"}[5m])) by (le, datasource))",
       "legendFormat": "{{ datasource }}"
      }
     ]
    },
    {
     "title": "Query response time - p75",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 41 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.75, sum(rate(druid_historical_query_time_ms_bucket{datasource=~\"$druid_datasource\"}[5m])) by (le, datasource))",
       "legendFormat": "{{ datasource }}"
      }
     ]
    },
    {
     "title": "Query response time - p90",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 41 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(rate(druid_historical_query_time_ms_bucket{instance=~\"druid.*:8000\", datasource=~\"$druid_datasource\"}[5m])) by (le, datasource))",
       "legendFormat": "{{ datasource }}"
      }
     ]
    },
    {
     "title": "Query response size - p50",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(rate(druid_historical_query_bytes_bucket{instance=~\"druid.*:8000\", datasource=~\"$druid_datasource\"}[5m])) by (le, datasource))",
       "legendFormat": "{{ datasource }}"
      }
     ]
    },
    {
     "title": "Query response size - p75",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 48 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.75, sum(rate(druid_historical_query_bytes_bucket{instance=~\"druid.*:8000\", datasource=~\"$druid_datasource\"}[5m])) by (le, datasource))",
       "legendFormat": "{{ datasource }}"
      }
     ]
    },
    {
     "title": "Query response size - p90",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 48 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.9, sum(rate(druid_historical_query_bytes_bucket{instance=~\"druid.*:8000\", datasource=~\"$druid_datasource\"}[5m])) by (le, datasource))",
       "legendFormat": "{{ datasource }}"
      }
     ]
    },
    {
     "title": "Query count (per second)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 55 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(idelta(druid_historical_query_time_ms_count{datasource=~\"$druid_datasource\"}[5m])) by (datasource)",
       "legendFormat": "{{ datasource }}"
      }
     ]
    },
    {
     "title": "Served segments size",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(druid_historical_segment_used_bytes{instance=~\"druid.*:8000\"}) by (datasource)",
       "legendFormat": "{{ datasource }}"
      }
     ]
    },
    {
     "title": "Served segments count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(druid_historical_segment_count{instance=~\"druid.*:8000\", datasource=~\"$druid_datasource\"}) by (datasource)",
       "legendFormat": "{{ datasource }}"
      }
     ]
    }
   ]
  },
  { "title": "Coordinator metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Available segments size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "druid_coordinator_segment_size_bytes{instance=~\"druid.*:8000\", datasource=~\"$druid_datasource\"}",
     "legendFormat": "{{ datasource }}"
    }
   ]
  },
  {
   "title": "Available segments count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "druid_coordinator_segment_count{instance=~\"druid.*:8000\", datasource=~\"$druid_datasource\"}",
     "legendFormat": "{{ datasource }}"
    }
   ]
  },
  {
   "title": "Segments dropped",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "druid_coordinator_segment_dropped_count{instance=~\"druid.*:8000\", datasource=~\"$druid_datasource\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Segments to load vs overshadowed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(druid_coordinator_segment_loadqueue_count{instance=~\"druid.*:8000\", datasource=~\"$druid_datasource\"}) by (datasource)",
     "legendFormat": "load queue"
    },
    {
     "expr": "sum(druid_coordinator_segment_overshadowed_count{instance=~\"druid.*:8000\", datasource=~\"$druid_datasource\"}) by (datasource)",
     "legendFormat": "overshadowed"
    }
   ]
  },
  {
   "title": "Segments unavailable",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(druid_coordinator_segment_unavailable_count{instance=~\"druid.*:8000\", datasource=~\"$druid_datasource\"}) by (datasource)",
     "legendFormat": "{{datasource}}"
    }
   ]
  },
  {
   "title": "Segments under replicated",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "min(druid_coordinator_segment_under_replicated_count{instance=~\"druid.*:8000\", datasource=~\"$druid_datasource\"}) by (datasource)",
     "legendFormat": "{{datasource}}"
    }
   ]
  },
  {
   "title": "Realtime",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processed events",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "druid_realtime_ingest_events_processed_count{instance=~\"druid.*:8000\", datasource=~\"$druid_datasource\"}",
       "legendFormat": "{{ datasource }}"
      }
     ]
    }
   ]
  },
  { "title": "Heap Used", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=\"broker:9123\", area=\"heap\"}",
     "legendFormat": "{{instance}} used"
    },
    {
     "expr": "jvm_memory_bytes_max{instance=\"broker:9123\", area=\"heap\"}",
     "legendFormat": "{{instance}} max"
    }
   ]
  },
  {
   "title": "Coordinator",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=\"coordinator:9123\", area=\"heap\"}",
     "legendFormat": "{{instance}} used"
    },
    {
     "expr": "jvm_memory_bytes_max{instance=\"coordinator:9123\", area=\"heap\"}",
     "legendFormat": "{{instance}} max"
    }
   ]
  },
  {
   "title": "Historical",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=\"historical:9123\", area=\"heap\"}",
     "legendFormat": "{{instance}} used"
    },
    {
     "expr": "jvm_memory_bytes_max{instance=\"historical:9123\", area=\"heap\"}",
     "legendFormat": "{{instance}} max"
    }
   ]
  },
  {
   "title": "Middle Manager",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=\"middlemanager1:9123\", area=\"heap\"}",
     "legendFormat": "{{instance}} used"
    },
    {
     "expr": "jvm_memory_bytes_max{instance=\"middlemanager2:9123\", area=\"heap\"}",
     "legendFormat": "{{instance}} max"
    }
   ]
  },
  {
   "title": "Overlord",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{instance=\"overlord:9123\", area=\"heap\"}",
     "legendFormat": "{{instance}} used"
    },
    {
     "expr": "jvm_memory_bytes_max{instance=\"overlord:9123\", area=\"heap\"}",
     "legendFormat": "{{instance}} max"
    }
   ]
  },
  { "title": "GC time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Broker",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{instance=\"broker:9123\"}[5m])",
     "legendFormat": "{{instance}} {{gc}}"
    }
   ]
  },
  {
   "title": "Coordinator",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 55 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{instance=\"coordinator:9123\"}[5m])",
     "legendFormat": "{{instance}} {{gc}}"
    }
   ]
  },
  {
   "title": "Historical",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 55 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{instance=\"historical:9123\"}[5m])",
     "legendFormat": "{{instance}} {{gc}}"
    }
   ]
  },
  {
   "title": "Middle Manager",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{instance=\"middlemanager1:9123\"}[5m])",
     "legendFormat": "{{instance}} {{gc}}"
    },
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{instance=\"middlemanager2:9123\"}[5m])",
     "legendFormat": "{{instance}} {{gc}}"
    }
   ]
  },
  {
   "title": "Overlord",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{instance=\"overlord:9123\"}[5m])",
     "legendFormat": "{{instance}} {{gc}}"
    }
   ]
  }
 ]
}