{
 "title": "Fedex Kafka Producer",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Message Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(fedex_kafka_producer_msg_count[1m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Data Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(fedex_kafka_producer_bytes_count[1m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(fedex_kafka_producer_error_count[1m])",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}