{
 "title": "adh-fedex",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Roadrunner Websocket Connection Teardowns/Rejections",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(roadrunner_websocket_teardown_count[$__interval])",
     "legendFormat": "{{connectorId}}-teardown"
    },
    {
     "expr": "rate(roadrunner_websocket_rejected_count[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Roadrunner rejected batches",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "rate(roadrunner_rejected_batches_due_to_bad_data_count[$__interval])",
     "legendFormat": "{{connectorId}}-teardown"
    },
    {
     "expr": "rate(roadrunner_rejected_batches_due_to_internal_errors_count[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "websocket read & ack time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(websocket_read_time_ms_bucket[$__interval])) by (tenant, hostname, zone, connectorId, instance, job)",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(websocket_ack_time_ms_bucket[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "histogram message process time",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(roadrunner_message_process_time_seconds_count[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "file processing time seconds",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(file_processing_time_seconds_bucket[$__interval])) by (hostname, tenant, zone, instance, job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "message_process_time_seconds_sum",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(roadrunner_message_process_time_seconds_sum[$__interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "kafka bytes count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(fedex_kafka_producer_bytes_count[$__range]) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "producer chan send time ms",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(producer_chan_send_time_ms_bucket[$__rate_interval])) by (tenant, hostname, zone, instance)) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "roadrunner mo's",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(roadrunner_mo_count[$__interval]) ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}