{
 "title": "Foxtrot Service",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Instances Up Status",
   "type": "timeseries",
   "description": "Drops means the service was not running",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"foxtrot-service\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "WS Server messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "foxtrot_ws_server_handle_duration_count",
     "legendFormat": "Message type \"{{message_type}}\" resulted in related HTTP code {{related_http_code}}"
    }
   ]
  },
  {
   "title": "WS Server messages duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "foxtrot_ws_server_handle_duration",
     "legendFormat": "Message type \"{{message_type}}\" resulted in HTTP code {{related_http_code}} in quantile {{quantile}} "
    }
   ]
  },
  {
   "title": "Postgres Call Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "foxtrot_postgres_method_call_duration",
     "legendFormat": "Method {{name}} in {{quantile}} quantile"
    }
   ]
  }
 ]
}