{
 "title": "GatherMetrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Ingestion Dict. and Profile validation violations",
   "type": "timeseries",
   "description": "Number of violations of ingestion profile & dictionary validation rules",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "gather_ingestion_profile_dict_violations",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Smart Incident Management Condition Rules",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "targets": [
    { "expr": "gather_sim_conditions_accepted", "legendFormat": "__auto" },
    { "expr": "gather_sim_conditions_declined", "legendFormat": "__auto" },
    { "expr": "gather_sim_conditions_created", "legendFormat": "__auto" },
    { "expr": "gather_conditions_created", "legendFormat": "__auto" },
    { "expr": "gather_sim_conditions_edited", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Postgres Call Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gather_postgres_method_call_duration"
    },
    {}
   ]
  },
  {
   "title": "API Call Duration",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "gather_api_call_duration", "legendFormat": "{{name}}:{{quantile}}" }
   ]
  },
  {
   "title": "Druid Call Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gather_druid_query_call_duration"
    },
    {}
   ]
  },
  {
   "title": "Druid DAO Method Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gather_druid_method_call_duration"
    }
   ]
  },
  {
   "title": "APIs by Service",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gather_admin_service_api_recieved_since_startup",
     "legendFormat": "admin_svc_rec"
    },
    {
     "expr": "gather_admin_service_api_completed_since_startup",
     "legendFormat": "admin_svc_fin"
    },
    {
     "expr": "gather_tenant_service_api_call_received_since_startup",
     "legendFormat": "tenant_svc_rec"
    },
    {
     "expr": "gather_tenant_service_api_call_completed_since_startup",
     "legendFormat": "tenant_svc_fin"
    },
    {
     "expr": "gather_metric_service_api_call_received_since_startup",
     "legendFormat": "metric_svc_rec"
    },
    {
     "expr": "gather_metric_service_api_call_completed_since_startup",
     "legendFormat": "metric_svc_fin"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"gather\"}",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Pouch API Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gather_pouch_changes_api_call_completed_since_startup",
     "legendFormat": "changes_fin"
    },
    {
     "expr": "gather_pouch_changes_api_call_received_since_startup",
     "legendFormat": "changes_rec"
    },
    {
     "expr": "gather_pouch_service_api_call_completed_since_startup",
     "legendFormat": "all_other_fin"
    },
    {
     "expr": "gather_pouch_service_api_call_received_since_startup",
     "legendFormat": "all_other_rec"
    }
   ]
  },
  {
   "title": "Total API Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gather_api_call_received_since_startup",
     "legendFormat": "gather_api_call_received_since_startup"
    },
    {
     "expr": "gather_api_call_completed_since_startup",
     "legendFormat": "gather_api_call_completed_since_startup"
    }
   ]
  }
 ]
}