{
 "title": "Go Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "Job", "query": "label_values(job)" }
  ]
 },
 "panels": [
  {
   "title": "GoRoutines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_goroutines{job=~'$job'}" }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=~'$job'}"
    }
   ]
  },
  {
   "title": "Next GC Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_next_gc_bytes{job=~'$job'}"
    }
   ]
  },
  {
   "title": "Heap Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=~'$job'}",
     "legendFormat": "go_memstats_heap_alloc_bytes({{job}})"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=~'$job'}",
     "legendFormat": "go_memstats_heap_inuse_bytes({{job}})"
    },
    {
     "expr": "go_memstats_heap_released_bytes{job=~'$job'}",
     "legendFormat": "go_memstats_heap_released_bytes({{job}})"
    }
   ]
  },
  {
   "title": "Heap Objects",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_objects{job=~'$job'}",
     "legendFormat": "go_memstats_heap_objects({{job}})"
    }
   ]
  },
  {
   "title": "Heap Allocation/Release",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{job=~'$job'}"
    },
    {
     "expr": "go_memstats_heap_released_bytes{job=~'$job'}"
    }
   ]
  },
  {
   "title": "Stack Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 5, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_stack_sys_bytes{job=~'$job'}"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=~'$job'}"
    }
   ]
  }
 ]
}