{
 "title": "Interceptor Condition Rules",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "tenant",
    "label": "tenant",
    "query": {
     "query": "label_values({__name__=~\".*gather_sim_.*|.*gather_conditions_.*\"}, tenantId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Accepted and Declined automated condition rules",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "gather_sim_conditions_accepted{tenantId=~\"$tenant\"}",
     "legendFormat": "Accepted condition rules"
    },
    {
     "expr": "gather_sim_conditions_declined{tenantId=~\"$tenant\"}",
     "legendFormat": "Declined condition rules"
    }
   ]
  },
  {
   "title": "Conditions created by SIM",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "gather_sim_conditions_created{tenantId=~\"$tenant\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Modified automated conditions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "gather_sim_conditions_edited{tenantId=~\"$tenant\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Conditions created by User",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "gather_conditions_created{tenantId=~\"$tenant\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Timeline of condition rules creation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 9, "y": 5 },
   "targets": [
    {
     "expr": "gather_sim_conditions_created{tenantId=~\"$tenant\"}",
     "legendFormat": "Condition rules are created automatically"
    },
    {
     "expr": "gather_conditions_created{tenantId=~\"$tenant\"}",
     "legendFormat": "Condition rules are created by User"
    }
   ]
  }
 ]
}