{
 "title": "Kafka Overview (JMX)",
 "tags": [ "Kafka" ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "customer topic",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_log_log_value{ name=\"LogEndOffset\" , topic = \"customer\" }) - sum(kafka_log_log_value{ name=\"LogStartOffset\", topic = \"customer\" })"
    }
   ]
  },
  {
   "title": "audit topic",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_log_log_value{ name=\"LogEndOffset\" , topic = \"audit\" }) - sum(kafka_log_log_value{ name=\"LogStartOffset\", topic = \"audit\" })"
    }
   ]
  },
  {
   "title": "Topic BytesIn to BytesOut Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_oneminuterate{name=\"BytesInPerSec\"}"
    },
    {
     "expr": "kafka_server_brokertopicmetrics_oneminuterate{name=\"BytesOutPerSec\"}"
    }
   ]
  },
  {
   "title": "Network Processor Idle (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "kafka_network_processor_value" }
   ]
  },
  {
   "title": "JVM Heap Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_memory_heapmemoryusage_used"
    }
   ]
  },
  {
   "title": "JVM System CPU Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "java_lang_operatingsystem_systemcpuload"
    }
   ]
  },
  {
   "title": "Total Partition Count",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_value{name=\"PartitionCount\"})"
    }
   ]
  },
  {
   "title": "Total Under Replicated Partition Count",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_value{name=\"UnderReplicatedPartitions\"})"
    }
   ]
  },
  {
   "title": "Kafka Broker Uptime",
   "type": "table",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 18 },
   "targets": [
    { "expr": "java_lang_runtime_uptime", "legendFormat": "Broker {{ instance }}" }
   ]
  },
  {
   "title": "Kafka Network Request Metrics",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_oneminuterate"
    }
   ]
  },
  {
   "title": "Max lag in messages btw follower and leader replicas",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_replicafetchermanager_value"
    }
   ]
  },
  {
   "title": "Request Handler Idle (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "kafka_server_kafkarequesthandlerpool_oneminuterate"
    }
   ]
  },
  {
   "title": "Kafka Broker Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 32 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    { "expr": "java_lang_runtime_uptime" }
   ]
  }
 ]
}