{
 "title": "Kubernetes Pod info",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_pod_info,namespace)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(kube_pod_info,node)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\"$namespace\", node=~\"$node\"},pod)"
    }
   },
   {
    "name": "pvc",
    "label": "pvc",
    "query": {
     "query": "query_result(kube_pod_spec_volumes_persistentvolumeclaims_info{namespace=~\"$namespace\", pod=~\"$pod\"}    * on(namespace, pod) group_left(node)      kube_pod_info{namespace=~\"$namespace\", node=~\"$node\"})"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pods",
   "type": "table",
   "gridPos": { "h": 17, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_pod_info{node=~\"$node\", namespace=~\"$namespace\", pod=~\"$pod\"}\n# attach the phase (Running/Pending/Succeeded/Failed/Unknown)\n* on(namespace, pod) group_left(phase)\n  (kube_pod_status_phase{namespace=~\"$namespace\"} == 1)\n# attach age in seconds\n* on(namespace, pod) group_left()\n  (time() - kube_pod_start_time{namespace=~\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "PVCs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "PVC usage (aggregated openebs-hostpath)",
   "type": "table",
   "gridPos": { "h": 15, "w": 16, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "(\n  ( 100 * kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"$pvc\",namespace=~\"$namespace\"}\n      / kubelet_volume_stats_capacity_bytes)\n  * on(namespace, persistentvolumeclaim) group_right()\n    max by(namespace, persistentvolumeclaim, pod, node) (\n      kube_pod_spec_volumes_persistentvolumeclaims_info\n        * on(namespace, pod) group_left(node) kube_pod_info{pod=~\"$pod\",node=~\"$node\"}\n    )\n)\n* on(namespace, persistentvolumeclaim) group_left(storageclass)\n  kube_persistentvolumeclaim_info",
     "legendFormat": "__auto"
    },
    {
     "expr": "kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"$pvc\",namespace=~\"$namespace\"}\n  * on(namespace, persistentvolumeclaim) group_right()\n    max by(namespace, persistentvolumeclaim, pod, node) (\n      kube_pod_spec_volumes_persistentvolumeclaims_info\n        * on(namespace, pod) group_left(node) kube_pod_info{pod=~\"$pod\",node=~\"$node\"}\n    )\n    * on(namespace, persistentvolumeclaim) group_left(storageclass)\n  kube_persistentvolumeclaim_info",
     "legendFormat": "__auto"
    },
    {
     "expr": "kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"$pvc\",namespace=~\"$namespace\"}\n* on(namespace, persistentvolumeclaim) group_right()\n    max by(namespace, persistentvolumeclaim, pod, node) (\n      kube_pod_spec_volumes_persistentvolumeclaims_info\n        * on(namespace, pod) group_left(node) kube_pod_info{pod=~\"$pod\",node=~\"$node\"}\n    )\n    * on(namespace, persistentvolumeclaim) group_left(storageclass)\n  kube_persistentvolumeclaim_info",
     "legendFormat": "__auto"
    },
    {
     "expr": "kube_persistentvolumeclaim_resource_requests_storage_bytes{persistentvolumeclaim=~\"$pvc\",namespace=~\"$namespace\"}\n* on(namespace, persistentvolumeclaim) group_right()\n    max by(namespace, persistentvolumeclaim, pod, node) (\n      kube_pod_spec_volumes_persistentvolumeclaims_info\n        * on(namespace, pod) group_left(node) kube_pod_info{pod=~\"$pod\",node=~\"$node\"}\n    )\n    * on(namespace, persistentvolumeclaim) group_left(storageclass)\n  kube_persistentvolumeclaim_info",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "pvc usage (refined openebs-hostpath)",
   "type": "table",
   "gridPos": { "h": 15, "w": 16, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "# ---- hostpath PVCs: openebs used / kubelet capacity ----\n(\n  100 *\n  (\n    openebs_hostpath_volume_used_bytes\n    * on(persistentvolume) group_left(namespace, persistentvolumeclaim)\n      label_replace(kube_persistentvolumeclaim_info, \"persistentvolume\", \"$1\", \"volumename\", \"(.+)\")\n  )\n  / on(namespace, persistentvolumeclaim) group_left()\n    kubelet_volume_stats_capacity_bytes\n)\n* on(namespace, persistentvolumeclaim) group_right()\n  max by(namespace, persistentvolumeclaim, pod, node) (\n    kube_pod_spec_volumes_persistentvolumeclaims_info\n      * on(namespace, pod) group_left(node) kube_pod_info{pod=~\"$pod\", node=~\"$node\"}\n  )\n* on(namespace, persistentvolumeclaim) group_left(storageclass)\n  kube_persistentvolumeclaim_info{storageclass=\"openebs-hostpath\", persistentvolumeclaim=~\"$pvc\", namespace=~\"$namespace\"}\n\nor\n\n# ---- non-hostpath PVCs: kubelet used / kubelet capacity ----\n(\n  ( 100 * kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"$pvc\", namespace=~\"$namespace\"}\n      / kubelet_volume_stats_capacity_bytes )\n  * on(namespace, persistentvolumeclaim) group_right()\n    max by(namespace, persistentvolumeclaim, pod, node) (\n      kube_pod_spec_volumes_persistentvolumeclaims_info\n        * on(namespace, pod) group_left(node) kube_pod_info{pod=~\"$pod\", node=~\"$node\"}\n    )\n)\n* on(namespace, persistentvolumeclaim) group_left(storageclass)\n  kube_persistentvolumeclaim_info{storageclass!=\"openebs-hostpath\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "# ---- hostpath PVCs: openebs used\n(\n    openebs_hostpath_volume_used_bytes\n    * on(persistentvolume) group_left(namespace, persistentvolumeclaim)\n      label_replace(kube_persistentvolumeclaim_info, \"persistentvolume\", \"$1\", \"volumename\", \"(.+)\")\n)\n* on(namespace, persistentvolumeclaim) group_right()\n  max by(namespace, persistentvolumeclaim, pod, node) (\n    kube_pod_spec_volumes_persistentvolumeclaims_info\n      * on(namespace, pod) group_left(node) kube_pod_info{pod=~\"$pod\", node=~\"$node\"}\n  )\n* on(namespace, persistentvolumeclaim) group_left(storageclass)\n  kube_persistentvolumeclaim_info{storageclass=\"openebs-hostpath\", persistentvolumeclaim=~\"$pvc\", namespace=~\"$namespace\"}\n\nor\n\n# ---- non-hostpath PVCs: kubelet used \n(\n  kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"$pvc\", namespace=~\"$namespace\"}\n      \n  * on(namespace, persistentvolumeclaim) group_right()\n    max by(namespace, persistentvolumeclaim, pod, node) (\n      kube_pod_spec_volumes_persistentvolumeclaims_info\n        * on(namespace, pod) group_left(node) kube_pod_info{pod=~\"$pod\", node=~\"$node\"}\n    )\n)\n* on(namespace, persistentvolumeclaim) group_left(storageclass)\n  kube_persistentvolumeclaim_info{storageclass!=\"openebs-hostpath\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "# ---- hostpath PVCs: kubelet capacity ----\n(\n    kubelet_volume_stats_capacity_bytes\n)\n* on(namespace, persistentvolumeclaim) group_right()\n  max by(namespace, persistentvolumeclaim, pod, node) (\n    kube_pod_spec_volumes_persistentvolumeclaims_info\n      * on(namespace, pod) group_left(node) kube_pod_info{pod=~\"$pod\", node=~\"$node\"}\n  )\n* on(namespace, persistentvolumeclaim) group_left(storageclass)\n  kube_persistentvolumeclaim_info{ persistentvolumeclaim=~\"$pvc\", namespace=~\"$namespace\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PVC usage (except openebs-hostpath)",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  ( 100 * kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"$pvc\",namespace=~\"$namespace\"}\n      / kubelet_volume_stats_capacity_bytes)\n  * on(namespace, persistentvolumeclaim) group_right()\n    max by(namespace, persistentvolumeclaim, pod, node) (\n      kube_pod_spec_volumes_persistentvolumeclaims_info\n        * on(namespace, pod) group_left(node) kube_pod_info{pod=~\"$pod\",node=~\"$node\"}\n    )\n)\n* on(namespace, persistentvolumeclaim) group_left(storageclass)\n  kube_persistentvolumeclaim_info{storageclass!=\"openebs-hostpath\"}",
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}}"
    },
    {}
   ]
  },
  {
   "title": "Openebs-hostpath disk usage - $node",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 59 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "quantile by(node) (0.5,\n  kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"$pvc\", namespace=~\"$namespace\"}\n  * on(namespace, persistentvolumeclaim) group_right()\n    max by(namespace, persistentvolumeclaim, pod, node) (\n      kube_pod_spec_volumes_persistentvolumeclaims_info\n        * on(namespace, pod) group_left(node) kube_pod_info{pod=~\"$pod\", node=~\"$node\"}\n    )\n)",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "quantile by(node) (0.5,\n  kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"$pvc\", namespace=~\"$namespace\"}\n  * on(namespace, persistentvolumeclaim) group_right()\n    max by(namespace, persistentvolumeclaim, pod, node) (\n      kube_pod_spec_volumes_persistentvolumeclaims_info\n        * on(namespace, pod) group_left(node) kube_pod_info{pod=~\"$pod\", node=~\"$node\"}\n    )\n)",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "quantile by(node) (0.5,\n100 * kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"$pvc\", namespace=~\"$namespace\"} /\n  kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"$pvc\", namespace=~\"$namespace\"}\n  * on(namespace, persistentvolumeclaim) group_right()\n    max by(namespace, persistentvolumeclaim, pod, node) (\n      kube_pod_spec_volumes_persistentvolumeclaims_info\n        * on(namespace, pod) group_left(node) kube_pod_info{pod=~\"$pod\", node=~\"$node\"}\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$node openebs-hostpath disk usage",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 69 },
   "repeat": "node",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "(\n    openebs_hostpath_volume_used_bytes\n    * on(persistentvolume) group_left(namespace, persistentvolumeclaim)\n      label_replace(kube_persistentvolumeclaim_info, \"persistentvolume\", \"$1\", \"volumename\", \"(.+)\")\n  )\n* on(namespace, persistentvolumeclaim) group_right()\n  max by(namespace, persistentvolumeclaim, pod, node) (\n    kube_pod_spec_volumes_persistentvolumeclaims_info{namespace=~\"$namespace\",persistentvolumeclaim=~\"$pvc\"}\n      * on(namespace, pod) group_left(node) kube_pod_info{pod=~\"$pod\", node=~\"$node\"}\n  )\n* on(namespace, persistentvolumeclaim) group_left(storageclass)\n  kube_persistentvolumeclaim_info",
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}}"
    },
    {
     "expr": "avg without(node)\n(quantile by(node) (0.5,\n  kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"$pvc\", namespace=~\"$namespace\"}\n  * on(namespace, persistentvolumeclaim) group_right()\n    max by(namespace, persistentvolumeclaim, pod, node) (\n      kube_pod_spec_volumes_persistentvolumeclaims_info\n        * on(namespace, pod) group_left(node) kube_pod_info{pod=~\"$pod\", node=~\"$node\"}\n    )\n))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "  # ---- hostpath PVCs: openebs used\n(\n    openebs_hostpath_volume_used_bytes\n    * on(persistentvolume) group_left(namespace, persistentvolumeclaim)\n      label_replace(kube_persistentvolumeclaim_info, \"persistentvolume\", \"$1\", \"volumename\", \"(.+)\")\n)\n* on(namespace, persistentvolumeclaim) group_right()\n  max by(namespace, persistentvolumeclaim, pod, node) (\n    kube_pod_spec_volumes_persistentvolumeclaims_info\n      * on(namespace, pod) group_left(node) kube_pod_info{pod=~\"$pod\", node=~\"$node\"}\n  )\n* on(namespace, persistentvolumeclaim) group_left(storageclass)\n  kube_persistentvolumeclaim_info{storageclass=\"openebs-hostpath\", persistentvolumeclaim=~\"$pvc\", namespace=~\"$namespace\"}\n\n",
     "legendFormat": "Usage {{persistentvolumeclaim}}"
    },
    {
     "expr": "# ---- non-hostpath PVCs: kubelet used \n(\n  kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"$pvc\", namespace=~\"$namespace\"}\n      \n  * on(namespace, persistentvolumeclaim) group_right()\n    max by(namespace, persistentvolumeclaim, pod, node) (\n      kube_pod_spec_volumes_persistentvolumeclaims_info\n        * on(namespace, pod) group_left(node) kube_pod_info{pod=~\"$pod\", node=~\"$node\"}\n    )\n)\n* on(namespace, persistentvolumeclaim) group_left(storageclass)\n  kube_persistentvolumeclaim_info{storageclass!=\"openebs-hostpath\"}",
     "legendFormat": "Usage {{persistentvolumeclaim}}"
    },
    {
     "expr": "\n(\n  kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"$pvc\", namespace=~\"$namespace\"}\n      \n  * on(namespace, persistentvolumeclaim) group_right()\n    max by(namespace, persistentvolumeclaim, pod, node) (\n      kube_pod_spec_volumes_persistentvolumeclaims_info\n        * on(namespace, pod) group_left(node) kube_pod_info{pod=~\"$pod\", node=~\"$node\"}\n    )\n)\n* on(namespace, persistentvolumeclaim) group_left(storageclass)\n  kube_persistentvolumeclaim_info{storageclass!=\"openebs-hostpath\"}",
     "legendFormat": "Capacity {{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "PVC Usage % over time",
   "type": "timeseries",
   "description": "Filesystem usage percentage for the selected PVC. Scoped by the namespace / pvc / pod variables passed from the PVC table drilldown.",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "# ---- hostpath PVCs: openebs used / kubelet capacity ----\n(\n  100 *\n  (\n    openebs_hostpath_volume_used_bytes\n    * on(persistentvolume) group_left(namespace, persistentvolumeclaim)\n      label_replace(kube_persistentvolumeclaim_info, \"persistentvolume\", \"$1\", \"volumename\", \"(.+)\")\n  )\n  / on(namespace, persistentvolumeclaim) group_left()\n    kubelet_volume_stats_capacity_bytes\n)\n* on(namespace, persistentvolumeclaim) group_right()\n  max by(namespace, persistentvolumeclaim, pod, node) (\n    kube_pod_spec_volumes_persistentvolumeclaims_info\n      * on(namespace, pod) group_left(node) kube_pod_info{pod=~\"$pod\", node=~\"$node\"}\n  )\n* on(namespace, persistentvolumeclaim) group_left(storageclass)\n  kube_persistentvolumeclaim_info{storageclass=\"openebs-hostpath\", persistentvolumeclaim=~\"$pvc\", namespace=~\"$namespace\"}",
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}}"
    },
    {
     "expr": "\n# ---- non-hostpath PVCs: kubelet used / kubelet capacity ----\n(\n  ( 100 * kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"$pvc\", namespace=~\"$namespace\"}\n      / kubelet_volume_stats_capacity_bytes )\n  * on(namespace, persistentvolumeclaim) group_right()\n    max by(namespace, persistentvolumeclaim, pod, node) (\n      kube_pod_spec_volumes_persistentvolumeclaims_info\n        * on(namespace, pod) group_left(node) kube_pod_info{pod=~\"$pod\", node=~\"$node\"}\n    )\n)\n* on(namespace, persistentvolumeclaim) group_left(storageclass)\n  kube_persistentvolumeclaim_info{storageclass!=\"openebs-hostpath\"}",
     "legendFormat": "{{namespace}}/{{persistentvolumeclaim}}"
    }
   ]
  }
 ]
}