{
 "title": "Pv Storage Inserted Datasets",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Prometheus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "PV Storage inserted Datasets to clickhouse (per CH nodes) rate 10m",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(pvstorage_inserted_datasets_total[10m])) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PV Storage inserted Datasets to clickhouse (per CH nodes) absolute value",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 15, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "sum((pvstorage_inserted_datasets_total)) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Click House Node  Up",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "(count (ClickHouseAsyncMetrics_Uptime))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Pvstorage Job running",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 9, "x": 9, "y": 14 },
   "targets": [
    {
     "expr": "count(sum(pvstorage_inserted_datasets_total) by (job))",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}