{
 "title": "PV Storage Flows",
 "description": "Number or rows and datasets per minute.",
 "tags": [ "pv-storage" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "tenant_id", "label": "tenant_id", "query": "label_values(tenant_id)" }
  ]
 },
 "panels": [
  {
   "title": "Rows",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(60*rate(pvstorage_inserted_rows_total{tenant_id=\"$tenant_id\"}[10m]))",
     "legendFormat": "Total inserted rows ({$tenant_id})"
    },
    {
     "expr": "sum(60*rate(pvstorage_inserted_rows_total{tenant_id=\"$tenant_id\"}[10m])) by (schema)",
     "legendFormat": "{{schema}} ({$tenant_id})"
    }
   ]
  },
  {
   "title": "Rows per pv-storage instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(60*rate(pvstorage_inserted_rows_total{tenant_id=\"$tenant_id\"}[10m])) by (job)",
     "legendFormat": "{{job}} ({$tenant_id})"
    }
   ]
  },
  {
   "title": "Inserted datasets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(60*rate(pvstorage_inserted_datasets_total{tenant_id=\"$tenant_id\"}[10m]))",
     "legendFormat": "Total datasets ({$tenant_id})"
    },
    {
     "expr": "sum(60*rate(pvstorage_inserted_datasets_total{tenant_id=\"$tenant_id\"}[10m])) by (schema)",
     "legendFormat": "{{schema}} ({$tenant_id})"
    }
   ]
  },
  {
   "title": "Inserted datasets per pv-storage instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(60*rate(pvstorage_inserted_datasets_total{tenant_id=\"$tenant_id\"}[10m])) by (job)",
     "legendFormat": "{{job}} ({$tenant_id})"
    }
   ]
  },
  {
   "title": "Invalid datasets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(60*rate(pvstorage_invalid_datasets_total{tenant_id=\"$tenant_id\"}[10m]))",
     "legendFormat": "Total invalid ({$tenant_id})"
    },
    {
     "expr": "sum(60*rate(pvstorage_invalid_datasets_total{tenant_id=\"$tenant_id\"}[10m])) by (schema)",
     "legendFormat": "{{schema}} ({$tenant_id})"
    }
   ]
  },
  {
   "title": "Invalid datasets per pv-storage instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(60*rate(pvstorage_invalid_datasets_total{tenant_id=\"$tenant_id\"}[10m])) by (job)",
     "legendFormat": "{{job}} ({$tenant_id})"
    }
   ]
  }
 ]
}