{
 "title": "Pyloth",
 "description": "Dashboard for Pyloth HTTP server",
 "tags": [ "pyloth" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "tenant_id", "label": "tenant_id", "query": "label_values(tenant_id)" }
  ]
 },
 "panels": [
  {
   "title": "Total requests per minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(pyloth_http_requests_total{tenant_id=~\"$tenant_id\", handler!=\"none\"}[1m])",
     "legendFormat": "{{ method }} {{ handler }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"pyloth\"}",
     "legendFormat": "mem"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"pyloth\"}[30s])",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(60*rate(pyloth_http_requests_total[10m]))",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(60*rate(pyloth_http_requests_total{tenant_id=~\"$tenant_id\"}[10m])) by (tenant_id)",
     "legendFormat": "{{tenant_id}}"
    }
   ]
  },
  {
   "title": "Error routes per tenant",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(60*rate(pyloth_http_requests_total{tenant_id=~\"$tenant_id\", status!=\"2xx\", handler!=\"none\"}[10m])) by (tenant_id)",
     "legendFormat": "All - {{handler}}"
    },
    {
     "expr": "sum(60*rate(pyloth_http_requests_total{tenant_id=~\"$tenant_id\", status!=\"2xx\", handler!=\"none\"}[10m])) by (tenant_id, handler)",
     "legendFormat": "{{tenant_id}} - {{handler}}"
    }
   ]
  },
  {
   "title": "Requested route per tenant",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(60*rate(pyloth_http_requests_total{tenant_id=~\"$tenant_id\"}[10m])) by (tenant_id, handler)",
     "legendFormat": "{{tenant_id}} - {{handler}}"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "pyloth_http_request_duration_seconds_sum{handler!=\"none\", tenant_id=~\"$tenant_id\"} / pyloth_http_request_duration_seconds_count{tenant_id=~\"$tenant_id\"}",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Request status per minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status, tenant_id) (rate(pyloth_http_requests_total{tenant_id=~\"$tenant_id\"}[1m]))",
     "legendFormat": "{{tenant_id}} - {{ status }}"
    }
   ]
  }
 ]
}