{
 "title": "Roadrunner",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Hostname", "query": "label_values(hostname)" }
  ]
 },
 "panels": [
  {
   "title": "Processing Rate",
   "type": "graph",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(roadrunner_mo_count{hostname=~\"$Hostname\"}[1m])",
     "legendFormat": "{{hostname}}-{{zone}}-RR MO Count - {{objectType}}"
    },
    {
     "expr": "increase(roadrunner_record_count{hostname=~\"$Hostname\"}[1m])",
     "legendFormat": "{{hostname}}-{{zone}}-RR Record Count - {{objectType}}"
    },
    {
     "expr": "increase(fedex_record_count{hostname=~\"$Hostname\"}[1m])",
     "legendFormat": "{{hostname}}-{{zone}}-Fedex Record Count - {{objectType}}"
    },
    {
     "expr": "sum(increase(fedex_record_count{hostname=~\"$Hostname\"}[1m]))",
     "legendFormat": "{{hostname}}-{{zone}}-Fedex Record Count - Total"
    }
   ]
  },
  {
   "title": "Current Roadrunner Status",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "targets": [
    { "expr": "roadrunner_connection" },
    { "expr": "foxtrot_connector_connected", "legendFormat": "__auto" },
    { "expr": "foxtrot_connector_configured", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Avg Processing time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(file_processing_time_seconds_sum{hostname=~\"$Hostname\"}[5m])/rate(file_processing_time_seconds_count{hostname=~\"$Hostname\"}[5m])",
     "legendFormat": "{{hostname}}-{{zone}}-{{tenant}}"
    }
   ]
  },
  {
   "title": "Roadrunner Connection Status",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "roadrunner_connection",
     "legendFormat": "{{hostname}}-{{zone}}-{{connectorId}}-{{tenant}}"
    }
   ]
  },
  {
   "title": "Roadrunner Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "roadrunner_available_system_memory{hostname=~\"$Hostname\"}",
     "legendFormat": "{{hostname}}-{{zone}}-{{tenant}}-Available"
    },
    {
     "expr": "roadrunner_total_system_memory{hostname=~\"$Hostname\"}",
     "legendFormat": "{{hostname}}-{{zone}}-{{tenant}}-Total"
    }
   ]
  },
  {
   "title": "Version and Cert Expiry",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "targets": [
    { "expr": "roadrunner_cert_expiry" }
   ]
  },
  {
   "title": "Roadrunner Data Dir Used %",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "roadrunner_disk_usage{hostname=~\"$Hostname\", path=~\"/dev/sdb\"}"
    }
   ]
  },
  {
   "title": "OpenMetricsScraper - Counters",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(oms_scrape_samples_post_metric_relabeling[5m])",
     "legendFormat": "Relabeling-{{hostname}}-{{zone}}-{{tenant}}-{{jobname}}-{{targetinstance}}"
    },
    {
     "expr": "rate(oms_scrape_samples_scraped[5m])",
     "legendFormat": "Samples-{{hostname}}-{{zone}}-{{tenant}}-{{jobname}}-{{targetinstance}}"
    },
    {
     "expr": "rate(oms_scrape_series_added[5m])",
     "legendFormat": "NewSeries-{{hostname}}-{{{{hostname}}-{{zone}}-{{tenant}}-{{jobname}}-{{targetinstance}}}}-{{tenant}}-{{jobname}}-{{instance}}"
    }
   ]
  },
  {
   "title": "OpenMetricsScraper - Connection Status",
   "type": "graph",
   "description": "Connectivity status for all scrape job targets",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "oms_up{hostname=~\"$Hostname\"}",
     "legendFormat": "{{hostname}}-{{zone}}-{{tenant}}-{{jobname}}-{{targetinstance}}"
    }
   ]
  },
  {
   "title": "OpenMetricsScraper - Scrape Duration",
   "type": "graph",
   "description": "Duration of each scrape job & target",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(oms_scrape_duration_seconds_sum{hostname=~\"$Hostname\"}[5m])/rate(oms_scrape_duration_seconds_count{hostname=~\"$Hostname\"}[5m])",
     "legendFormat": "{{hostname}}-{{zone}}-{{tenant}}-{{jobname}}-{{targetinstance}}"
    }
   ]
  },
  {
   "title": "Persistence Service - Cache Size (bytes)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "roadrunner_persistence_service_cache_size_bytes"
    }
   ]
  },
  {
   "title": "Persistence Service - Data Files",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "roadrunner_persistence_service_cached_files"
    }
   ]
  },
  {
   "title": "Persistence Service - Outstanding Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "roadrunner_persistence_service_outstanding_requests"
    }
   ]
  },
  {
   "title": "Snmp Trap not sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "targets": [
    {
     "expr": "roadrunner_snmp_traps_not_sent_count",
     "legendFormat": "{{hostname}}-{{zone}}-{{connectorId}}"
    }
   ]
  },
  {
   "title": "Snmp Trap sent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "targets": [
    {
     "expr": "roadrunner_snmp_traps_successfully_sent_count",
     "legendFormat": "{{hostname}}-{{zone}}-{{connectorId}}"
    }
   ]
  },
  {
   "title": "MQTT Messages not consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "targets": [
    {
     "expr": "roadrunner_mqtt_messages_not_consumed_count",
     "legendFormat": "{{hostname}}-{{zone}}-{{connectorId}}"
    }
   ]
  },
  {
   "title": "MQTT Messages successfully consumed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "targets": [
    {
     "expr": "roadrunner_mqtt_messages_successfully_consumed_count",
     "legendFormat": "{{hostname}}-{{zone}}-{{connectorId}}"
    }
   ]
  },
  {
   "title": "MQTT Service stop count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "targets": [
    {
     "expr": "roadrunner_mqtt_service_stop_count",
     "legendFormat": "{{hostname}}-{{zone}}-{{connectorId}}"
    }
   ]
  },
  {
   "title": "MQTT Service initialization count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "targets": [
    {
     "expr": "roadrunner_mqtt_service_initialization_count",
     "legendFormat": "{{hostname}}-{{zone}}-{{connectorId}}"
    }
   ]
  },
  {
   "title": "SNMP Service stop count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "targets": [
    {
     "expr": "roadrunner_snmp_service_stop_count",
     "legendFormat": "{{hostname}}-{{zone}}-{{connectorId}}"
    }
   ]
  },
  {
   "title": "SNMP Service initialization count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "targets": [
    {
     "expr": "roadrunner_snmp_service_initialization_count",
     "legendFormat": "{{hostname}}-{{zone}}-{{connectorId}}"
    }
   ]
  },
  {
   "title": "CSV Validation Results",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
   "targets": [
    {
     "expr": "roadrunner_csv_validation_result",
     "legendFormat": "{{hostname}}-{{zone}}-{{connectorId}}-{{reason}}"
    }
   ]
  }
 ]
}