{
 "title": "Roadrunner data flow",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Configuration issues",
   "type": "timeseries",
   "description": "Flat line is ok. It increases when Roadrunner can not get the configuration.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "roadrunner_configuration_error",
     "legendFormat": "hostname={{hostname}} tenant={{tenant}} connectorId={{connectorId}} zone={{zone}} instance={{instance}}"
    }
   ]
  },
  {
   "title": "Foxtrot connection",
   "type": "timeseries",
   "description": "It increases on successful connection with Foxtrot. Decreases in case of connection issues.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "roadrunner_foxtrot_connection_status",
     "legendFormat": "hostname={{hostname}} tenant={{tenant}} connectorId={{connectorId}} zone={{zone}} instance={{instance}}"
    }
   ]
  },
  {
   "title": "Dropped data",
   "type": "timeseries",
   "description": "Increases (with reason label) when Roadrunner drops data.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "roadrunner_data_dropped_count",
     "legendFormat": "reason={{reason}} hostname={{hostname}} tenant={{tenant}} connectorId={{connectorId}} zone={{zone}} instance={{instance}}"
    }
   ]
  },
  {
   "title": "MQTT connection status",
   "type": "timeseries",
   "description": "It increases on successful connection with MQTT. Decreases in case of connection issues.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "roadrunner_mqtt_connection_status",
     "legendFormat": "hostname={{hostname}} tenant={{tenant}} connectorId={{connectorId}} zone={{zone}} instance={{instance}}"
    }
   ]
  },
  {
   "title": "Open Metrics Scraper channel load",
   "type": "timeseries",
   "description": "The ratio of queued items to Golang channel capacity.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "roadrunner_open_metrics_scraper_channel_load_percentage",
     "legendFormat": "hostname={{hostname}} tenant={{tenant}} connectorId={{connectorId}} zone={{zone}} instance={{instance}}"
    }
   ]
  }
 ]
}