{
 "title": "Roadrunner",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Hostname", "query": "label_values(hostname)" }
  ]
 },
 "panels": [
  {
   "title": "Roadrunner Processing Rate",
   "type": "graph",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(roadrunner_mo_count{hostname=~\"$Hostname\"}[5m])",
     "legendFormat": "{{hostname}}-{{zone}}-RR MO Count - {{objectType}}"
    },
    {
     "expr": "increase(roadrunner_record_count{hostname=~\"$Hostname\"}[5m])",
     "legendFormat": "{{hostname}}-{{zone}}-RR Record Count - {{objectType}}"
    },
    {
     "expr": "increase(fedex_record_count{hostname=~\"$Hostname\"}[5m])",
     "legendFormat": "{{hostname}}-{{zone}}-Fedex Record Count - {{objectType}}"
    },
    {
     "expr": "sum(increase(fedex_record_count{hostname=~\"$Hostname\"}[5m]))",
     "legendFormat": "{{hostname}}-{{zone}}-Fedex Record Total"
    }
   ]
  },
  {
   "title": "Current Roadrunner Status",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "targets": [
    { "expr": "roadrunner_connection" }
   ]
  },
  {
   "title": "Avg Processing time",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(file_processing_time_seconds_sum{hostname=~\"$Hostname\"}[5m])/rate(file_processing_time_seconds_count{hostname=~\"$Hostname\"}[5m])",
     "legendFormat": "{{hostname}}-{{zone}}-{{tenant}}"
    }
   ]
  },
  {
   "title": "Roadrunner Connection Status",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "roadrunner_connection",
     "legendFormat": "{{hostname}}-{{zone}}-{{tenant}}"
    }
   ]
  },
  {
   "title": "Roadrunner Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "roadrunner_available_system_memory{hostname=~\"$Hostname\"}",
     "legendFormat": "{{hostname}}-{{zone}}-{{tenant}}-Available"
    },
    {
     "expr": "roadrunner_total_system_memory{hostname=~\"$Hostname\"}",
     "legendFormat": "{{hostname}}-{{zone}}-{{tenant}}-Total"
    }
   ]
  },
  {
   "title": "Version and Cert Expiry",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "targets": [
    { "expr": "roadrunner_cert_expiry" }
   ]
  },
  {
   "title": "Roadrunner Data Dir Used %",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 51 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "roadrunner_disk_usage{hostname=~\"$Hostname\", path=~\"/dev/sdb\"}"
    }
   ]
  }
 ]
}