{
 "title": "Routing Analytics Collector Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Latest Aggregation Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "message_agentHealth_AggregationTimePerReductionCount_0",
     "legendFormat": "Agent: {{agentId}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "message_agentHealth_SensorAgentStatusSet",
     "legendFormat": "{{agentId}}"
    },
    {
     "expr": "message_agentHealth_RoutingAnalyticsStatusSet",
     "legendFormat": "{{agentId}}"
    },
    {
     "expr": "message_agentHealth_CurrentNumLinksSet",
     "legendFormat": "{{agentId}}"
    },
    {
     "expr": "message_agentHealth_CurrentUpdateCadenceSet",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumed Topology Events Number",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "message_agentHealth_ConsumedTopologyEventsCount",
     "legendFormat": "Agent: {{agentId}}"
    }
   ]
  },
  {
   "title": "Duplicated Topology Events Number",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "message_agentHealth_DuplicatedTopologyEventsCount",
     "legendFormat": "Agent: {{agentId}}"
    }
   ]
  },
  {
   "title": "Unprovisioned Topology Events Number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "message_agentHealth_UnprovisionedTopologyEventsCount",
     "legendFormat": "Agent: {{agentId}}"
    }
   ]
  },
  {
   "title": "Aggregated Topology Events Number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "message_agentHealth_AggregatedTopologyEventsCount",
     "legendFormat": "Agent: {{agentId}}"
    }
   ]
  },
  {
   "title": "Successfully Sent Topology Events Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "message_agentHealth_SuccessfullySentEventsCount",
     "legendFormat": "Agent: {{agentId}}"
    }
   ]
  },
  {
   "title": "Unsuccessfully Sent Topology Events Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "message_agentHealth_UnsuccessfullySentEventsCount",
     "legendFormat": "Agent: {{agentId}}"
    }
   ]
  }
 ]
}