{
 "title": "Sky-Topo",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "Nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sky_topo_max_nodes", "legendFormat": "{{tenant_id}} - Max Nodes" },
    {
     "expr": "sky_topo_current_nodes",
     "legendFormat": "{{tenant_id}} - Nodes ({{state}})"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(sky_topo_errors_total[$__rate_interval])",
     "legendFormat": "{{tenant_id}}-{{error_code}}"
    }
   ]
  },
  {
   "title": "Records Processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(sky_topo_records_processed_total[$__rate_interval])",
     "legendFormat": "{{tenant_id}}-{{record_type}}"
    }
   ]
  },
  {
   "title": "Node Provisioning Avg Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(sky_topo_node_provisioning_duration_seconds_sum[$__interval])/rate(sky_topo_node_provisioning_duration_seconds_count[$__interval])",
     "legendFormat": "{{tenant_id}}"
    }
   ]
  },
  {
   "title": "Druid Supervisor Healthy",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    { "expr": "druid_supervisor_healthy", "legendFormat": "{{id}}" }
   ]
  }
 ]
}