{
 "title": "Sky Topo Node Processor",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Available (supported - with routing analytics config defined) agents.",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_processor_available_agents",
     "legendFormat": "tenant_id: {{tenant_id}}"
    }
   ]
  },
  {
   "title": "Available (supported - with routing analytics config defined) agents.",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 20, "x": 7, "y": 0 },
   "targets": [
    {
     "expr": "node_processor_available_agents",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All segments in both orientations.",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_processor_all_segments", "legendFormat": "tenant_id: {{tenant_id}}" }
   ]
  },
  {
   "title": "All segments in both orientations.",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 20, "x": 7, "y": 5 },
   "targets": [
    { "expr": "node_processor_all_segments", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Segments (in both orientations) per agent we aim to.",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_processor_segments_per_agent_we_aim_to",
     "legendFormat": "tenant_id: {{tenant_id}}"
    }
   ]
  },
  {
   "title": "Segments (in both orientations) per agent we aim to.",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 20, "x": 7, "y": 10 },
   "targets": [
    {
     "expr": "node_processor_segments_per_agent_we_aim_to",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Not assigned segments in both orientations.",
   "type": "gauge",
   "description": "High value may indicate lags.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_processor_not_assigned_segments",
     "legendFormat": "tenant_id: {{tenant_id}}"
    }
   ]
  },
  {
   "title": "Not assigned segments in both orientations.",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 20, "x": 7, "y": 14 },
   "targets": [
    {
     "expr": "node_processor_not_assigned_segments",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}