{
 "title": "Skylight-AAA",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Certificates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Client Certificate Statuses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "skylight_aaa_client_certificates_active",
     "legendFormat": "Active: {{tenantId}}"
    },
    {
     "expr": "skylight_aaa_client_certificates_revoked",
     "legendFormat": "Revoked: {{tenantId}}"
    },
    {
     "expr": "skylight_aaa_client_certificates_issued_total",
     "legendFormat": "Total: {{tenantId}}"
    },
    {
     "expr": "skylight_aaa_client_certificates_ocsp_status",
     "legendFormat": "OCSP Status: {{status}} {{tenantId}}"
    }
   ]
  },
  {
   "title": "Tenant Certificate Expiry Days",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "skylight_aaa_tenant_cert_expiry_days",
     "legendFormat": "Tenant Certificate Expiry Days: {{tenantId}}"
    }
   ]
  },
  { "title": "API Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "API Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "skylight_aaa_api_call_received_since_startup",
     "legendFormat": "{{api}}"
    },
    {
     "expr": "skylight_aaa_rejected_cert_authorization_requests",
     "legendFormat": "Rejected Cert Authorization Requests"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "skylight_aaa_user_cache_hits", "legendFormat": "Hits" },
    { "expr": "skylight_aaa_user_cache_miss", "legendFormat": "Misses" }
   ]
  },
  {
   "title": "API Request Duration Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "skylight_aaa_api_call_duration_count",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "API Request Duration Sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "skylight_aaa_api_call_duration_sum",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}