{
 "title": "Spark Resources",
 "tags": [ "spark" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "AppName", "query": "label_values(job)" },
   { "name": "ExecutorId", "query": "label_values(number)" }
  ]
 },
 "panels": [
  {
   "title": "Executor $ExecutorId Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "repeat": "ExecutorId",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(spark_jvm_total_used{job=\"spark_$AppName\", role=\"executor\", number=\"$ExecutorId\"})",
     "legendFormat": "used"
    },
    {
     "expr": "spark_jvm_heap_max{job=\"spark_$AppName\", role=\"executor\", number=\"$ExecutorId\"}",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "Executor $ExecutorId Tasks (i.e utilization of cores)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "repeat": "ExecutorId",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(spark_executor_threadpool_activeTasks{job=\"spark_$AppName\", number=\"$ExecutorId\", role=\"executor\"})",
     "legendFormat": "active tasks"
    },
    {
     "expr": "sum(spark_executor_threadpool_currentPool_size{job=\"spark_$AppName\", number=\"$ExecutorId\",role=\"executor\"})",
     "legendFormat": "task pool size"
    },
    {}
   ]
  },
  {
   "title": "Driver Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "spark_jvm_total_used{job=\"spark_$AppName\", role=\"driver\"}",
     "legendFormat": "used"
    },
    {
     "expr": "spark_jvm_heap_max{job=\"spark_$AppName\", role=\"driver\"}",
     "legendFormat": "max"
    }
   ]
  }
 ]
}