{
 "title": "Spark Ingestion and Lag",
 "tags": [ "spark" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "RecordCount",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(spark_AccedianStreamingMetrics_streaming_recCount{job=\"spark_streamingapp\"}[1m])",
     "legendFormat": "{{job}} {{objectType}}"
    },
    {
     "expr": "rate(spark_AccedianStreamingMetrics_streaming_recCount{job=\"spark_latentapp\"}[1m])",
     "legendFormat": "{{job}} {{objectType}}"
    }
   ]
  },
  {
   "title": "Lag",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 11, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(spark_kafkaProcessingLag{job=\"SparkKafkaLagMonitor\", topic=~\"spark_raw_in.*\"}[2m])",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "avg_over_time(spark_kafkaProcessingLag{job=\"SparkKafkaLagMonitor\", topic=\"alert-events\"}[2m])",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "spark_kafkaProcessingLag{job=\"SparkKafkaLagMonitor\", topic=~\".*latent.*[\\\\.].*\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Ingestion Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_server_brokertopicmetrics_oneminuterate{name=\"MessagesInPerSec\", topic=~\"npav-ts-metrics.*|spark_raw_in.*|parquet-notif|latent_raw_in.*|spark-latent.*\"}",
     "legendFormat": "{{topic}}"
    },
    {},
    {}
   ]
  },
  {
   "title": "Batch Job Work Queue Lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "spark_batchJobLag{queue=~\".*_queue\"}",
     "legendFormat": "{{queue}}"
    }
   ]
  },
  {
   "title": "Dropped Record Counts",
   "type": "table",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum by(job, tenant,objectType, cause) (spark_AccedianStreamingMetrics_streaming_droppedRecCount)"
    },
    {
     "expr": "spark_AccedianStreamingMetrics_streaming_droppedRecCount - spark_AccedianStreamingMetrics_streaming_droppedRecCount offset $__interval >= 0"
    }
   ]
  },
  {
   "title": "Spark Local Disk Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100.0 - 100 * (node_filesystem_avail{instance=~'.*hdfsdata.*', device !~'tmpfs',device!~'by-uuid', mountpoint=\"/mnt/spark\"} / node_filesystem_size{instance=~'.*hdfsdata.*', device !~'tmpfs',device!~'by-uuid', mountpoint=\"/mnt/spark\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Micro Batch Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 5, "y": 27 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "spark_queryBatchDuration{job=\"spark_streamingapp\"}",
     "legendFormat": "raw batch duration {{query}}"
    },
    {
     "expr": "spark_queryBatchDuration{job=\"spark_latentapp\"}",
     "legendFormat": "latent batch duration"
    }
   ]
  }
 ]
}