{
 "title": "Spark",
 "tags": [ "spark" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "job", "query": "label_values(job)" },
   { "name": "role", "query": "label_values(role)" }
  ]
 },
 "panels": [
  {
   "title": "Total Processed Records (from spark_raw_in)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "spark_streaming_totalProcessedRecords"
    }
   ]
  },
  {
   "title": "Spark Ingestion Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 5, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(spark_streaming_totalProcessedRecords{job=\"spark_$job\"}[10m]))\n",
     "legendFormat": "totalProcessed"
    },
    {
     "expr": "avg(rate(spark_streaming_totalReceivedRecords{job=\"spark_$job\"}[10m]))",
     "legendFormat": "totalReceived"
    }
   ]
  },
  {
   "title": "Kafka Ingestion Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(kafka_server_brokertopicmetrics_oneminuterate{topic=\"npav-ts-metrics\", name=\"MessagesInPerSec\"}[5m])",
     "legendFormat": "npav-ts-metrics"
    },
    {
     "expr": "avg_over_time(kafka_server_brokertopicmetrics_oneminuterate{topic=\"spark_raw_in\", name=\"MessagesInPerSec\"}[5m])",
     "legendFormat": "spark_raw_in"
    }
   ]
  },
  {
   "title": "Batch Timing",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(spark_streaming_lastCompletedBatch_totalDelay{job=\"spark_$job\"}[5m])",
     "legendFormat": "totalDelay"
    },
    {
     "expr": "avg_over_time(spark_streaming_lastCompletedBatch_schedulingDelay{job=\"spark_$job\"}[5m])",
     "legendFormat": "schedulingDelay"
    },
    {
     "expr": "avg_over_time(spark_streaming_lastCompletedBatch_processingDelay{job=\"spark_$job\"}[5m])",
     "legendFormat": "processingDelay"
    }
   ]
  },
  {
   "title": "Executor Active Tasks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(spark_executor_threadpool_currentPool_size{job=\"spark_$job\"}[10m])",
     "legendFormat": "current pool size"
    },
    {
     "expr": "avg_over_time(spark_executor_threadpool_activeTasks{job=\"spark_$job\"}[10m])",
     "legendFormat": "active tasks"
    }
   ]
  },
  {
   "title": "Memory Utilization $role",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "repeat": "role",
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "spark_jvm_total_used{job=\"spark_$job\", role=\"$role\"}"
    },
    {
     "expr": "spark_jvm_total_max{job=\"spark_$job\", role=\"$role\"}"
    }
   ]
  },
  {
   "title": "Batch Stats",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "spark_streaming_waitingBatches" },
    { "expr": "spark_streaming_runningBatches" },
    {
     "expr": "spark_streaming_unprocessedBatches"
    },
    {}
   ]
  }
 ]
}