{
 "title": "SSH Logins",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "deployment_url", "query": "https://njl.npav.accedian.net" }
  ]
 },
 "panels": [
  {
   "title": "Total SSH Logins via Vault",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "Accepted",
     "bucketAggs": [
      {
       "$$hashKey": "object:210",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:208", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "system.auth.ssh.event:\"Accepted\" and system.auth.ssh.event:\"Accepted\" and not system.auth.ssh.signature:*vault*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Total SSH Logins NOT using Vault",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "alias": "Accepted",
     "bucketAggs": [
      {
       "$$hashKey": "object:210",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:208", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "!system.auth.ssh.signature:*vault* and system.auth.ssh.event:\"Accepted\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SSH Login Attempts by Country and Provider",
   "type": "table",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "$$hashKey": "object:1539",
       "fake": true,
       "field": "system.auth.ssh.event",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:1917",
       "fake": true,
       "field": "source.geo.country_iso_code",
       "id": "6",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "10" },
       "type": "terms"
      },
      {
       "$$hashKey": "object:998",
       "fake": true,
       "field": "source.as.organization.name",
       "id": "4",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "_count",
        "size": "0"
       },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "$$hashKey": "object:937",
       "field": "select field",
       "id": "3",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "system.auth.ssh.event:*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SSH Logins NOT using Vault",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "SSH Login NOT using Vault",
     "bucketAggs": [
      {
       "$$hashKey": "object:1391",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:1389", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "system.auth.ssh.event:\"Accepted\" and !system.auth.ssh.signature:*vault*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "SSH Login Attempts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Invalid SSH Logins",
     "bucketAggs": [
      {
       "$$hashKey": "object:1391",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:1389", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "system.auth.ssh.event:\"Invalid\"",
     "timeField": "@timestamp"
    },
    {
     "alias": "Failed SSH Logins",
     "bucketAggs": [
      {
       "$$hashKey": "object:199",
       "field": "@timestamp",
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "$$hashKey": "object:197", "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "system.auth.ssh.event:\"Failed\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}