{
 "title": "update server",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15m",
 "panels": [
  {
   "title": "RR Update rolled back",
   "type": "timeseries",
   "description": "RR reverted to the previous version. (rolled back update)",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "roadrunner_update_rolled_back{job=\"roadrunner_update_server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Connected clients ( over websocket )",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "websocket_connected_clients{job=\"roadrunner_update_server\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "roadrunner_update_required_checks_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Roadrunners to be updated",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 6 },
   "targets": [
    {
     "expr": "sum (roadrunner_update_enabled)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory allocation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"roadrunner_update_server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Roadrunner fetch time",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (roadrunner_version) (roadrunner_fetch_from_registry_seconds{quantile=\"0.9\", job=\"roadrunner_update_server\"})",
     "legendFormat": "{{roadrunner_version}}"
    }
   ]
  },
  {
   "title": "Checking for available  update per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum(rate(roadrunner_update_required_checks_total{}[2m])) by (job)",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Http Errors - % (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(echo_http_requests_total{status=\"5xx\"}[5m])) / sum(rate(echo_http_requests_total{}[5m])) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Latency by handler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (job, method, handler, le) (rate(echo_http_request_duration_seconds_bucket{job=\"roadrunner_update_server\"} [5m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}