{
 "title": "Weld-watcher",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Cron Job Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(weld_watcher_cron_http_status) by (tenant_id, statusCode, error)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cron Job Errors",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "weld_watcher_cron_http_status", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP Response Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(weld_watcher_http_status) by (tenant_id, statusCode, route, method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Response Statuses",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(weld_watcher_http_status) by (tenant_id, statusCode, route, method)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}