{
 "title": "Weld-Watcher: Concurrent Users on Dashboard Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Average Number of Dashboard Loads by Tenant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(weld_watcher_dashboard_load_time_count[5m]) * 60) by (tenant_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Concurrent User Dashboard Load By Tenant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(weld_watcher_dashboard_load_unique_user) by (tenant_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worst Performing Dashboards",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "(topk(10, sum by(dashboard_id, tenant_id) (rate(weld_watcher_dashboard_load_time_sum[5m])) !=0) * 60) / (sum by(dashboard_id, tenant_id) (rate(weld_watcher_dashboard_load_time_count[5m])!=0) * 60)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Dashboard Load Times (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "(sum(rate(weld_watcher_dashboard_load_time_sum[5m]) * 60) by (dashboard_id)!=0) / (sum(rate(weld_watcher_dashboard_load_time_count[5m]) * 60) by (dashboard_id)!=0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average Dashboard Load Times (ms) by Tenant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(weld_watcher_dashboard_load_time_sum[5m]) * 60) by (tenant_id) / sum(rate(weld_watcher_dashboard_load_time_count[5m]) * 60) by (tenant_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Unique Dashboards Loaded by Tenant",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(weld_watcher_dashboard_load_time_sum[5m]) != 0) by (tenant_id)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}