{
 "title": "General Deployment Overview",
 "description": "Main KPI for Deployment system",
 "tags": [
  "Overview",
  "sre-monitored"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Session Count Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "gather_metric_ds_last_hour_numObjects_per_type",
     "legendFormat": "{{tenantId}} - {{objectType}} "
    }
   ]
  },
  {
   "title": "Flows per Tenant",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(60*rate(pvstorage_inserted_rows_total[1h])) by (tenant_id)"
    }
   ]
  },
  {
   "title": "Raw Record Consumed",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "spark_AccedianStreamingMetrics_streaming_rawRecsConsumed"
    }
   ]
  },
  {
   "title": "Size of Last Registered backup",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "skylight_backups_size_of_last_backups{backup_type=\"gather\"}",
     "legendFormat": "{{backup_type}}"
    },
    {
     "expr": "skylight_backups_size_of_last_backups{backup_type=\"postgres\"}",
     "legendFormat": "{{backup_type}}"
    }
   ]
  },
  {
   "title": "Time since last backup",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "skylight_backups_time_since_last_backup",
     "legendFormat": "{{backup_type}}"
    }
   ]
  },
  {
   "title": "Number of backups stored",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 17, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "skylight_backups_number_of_backups{}",
     "legendFormat": "{{backup_type}}"
    }
   ]
  },
  {
   "title": "1 Day Cert Expiry",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(probe_ssl_earliest_cert_expiry - time())/60/60/24",
     "legendFormat": "# of days until cert expires"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 17, "x": 5, "y": 16 },
   "options": { "content": "# RoadRunner" },
   "targets": [
    {}
   ]
  },
  {
   "title": "RoadRunner Connectivity",
   "type": "graph",
   "gridPos": { "h": 10, "w": 10, "x": 5, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "roadrunner_connection{hostname!=\"PVX\", hostname!=\"ACC-SPAV02LX-LV\", hostname!=\"012-JC-SKYLIGHT-CAPTURE\", hostname!=\"07-HOU-SKYLIGHT-CAPTURE\", hostname!=\"08-ANG-SKYLIGHT-CAPTURE\", hostname!=\"10-MIA-SKYLIGHT-CAPTURE\", hostname!=\"112-PA-SKYLIGHT-CAPTURE\", hostname!=\"13-ATL-SKYLIGHT-CAPTURE\", hostname!=\"14-COI-SKYLIGHT-CAPTURE\", hostname!=\"15-SEC-SKYLIGHT-CAPTURE\", hostname!=\"17-VA-SKYLIGHT-CAPTURE\", hostname!=\"acc-capture-lon-02-02\", hostname!=\"acc-capture-lon-03\", hostname!=\"acc-capture-lon-04\", hostname!=\"acc-capture-ny1-01\", hostname!=\"acc-capture-ny2-01\", hostname!=\"acc-capture-se2-01\", hostname!=\"acc-capture-sv2-01\", hostname!=\"acc-capture-sv2-02\", hostname!=\"acc-capture-tx-01\", hostname!=\"gpcom.analytics.accedian.io\", hostname!=\"18-BOL-SKYLIGHT-CAPTURE\", hostname!=\"22-APO-SKYLIGHT-CAPTURE\", hostname!=\"05-MA-SKYLIGHT-CAPTURE\", hostname!=\"GeorgeSOHO\", hostname!=\"44-SJ-SKYLIGHT-CAPTURE\",hostname!=\"SpursDC\", hostname!=\"PVX-Datastore\", hostname!=\"ACC-SPAV02LX-LV\", hostname!=\"ACC-SPVX01-C3\", hostname!=\"ACC-SPVX01-LV\", hostname!=\"Rochelle\", hostname!=\"ACC-SPVX01-C3\", hostname!=\"SpursDC01\",  hostname!=\"acc-capture-lon-01\", hostname!=\"acc-capture-lon-01-02\", hostname!=\"acc-capture-lon-02\", hostname!=\"SpursDC2\", hostname!=\"entel-cl.analytics.accedian.io\", zone!=\"SampleDataTest\", zone!=\"Cisco-John\", tenant!=\"bd8e9e41-e62f-4beb-9d48-2324b3ae623b\", tenant!=\"f19b6ec7-8bcf-4a95-98e7-dffa97ea16f9\"}",
     "legendFormat": "{{hostname}} / {{tenant}} / {{zone}}"
    }
   ]
  },
  {
   "title": "Roadrunner Processing Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 18 },
   "targets": [
    {
     "expr": "sum(increase(roadrunner_mo_count{zone=~\".*\"}[5m])) by (hostname, zone)",
     "legendFormat": "{{hostname}}-{{zone}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 17, "x": 5, "y": 28 },
   "options": { "content": "# Ingestion Statistics" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Spark Kafka Ingestion and Lag",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 5, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(spark_kafkaProcessingLag{job=\"SparkKafkaLagMonitor\", topic!=\"parquet-notif\", topic!~\"spark_raw_in.*\", topic!~\".*latent.*\", consumer!=\"appender\", consumer!=\"aggregation-PT1M\", consumer!=\"aggregation-PT15M\", topic!=\"spark_raw_in.f19b6ec7-8bcf-4a95-98e7-dffa97ea16f9.regulator\"}[2m])",
     "legendFormat": "{{consumer}} {{topic}}"
    },
    {
     "expr": "avg_over_time(spark_kafkaProcessingLag{job=\"SparkKafkaLagMonitor\", topic=~\"spark_raw_in.*\", topic!=\"spark_raw_in.f19b6ec7-8bcf-4a95-98e7-dffa97ea16f9.regulator\"}[2m])",
     "legendFormat": "{{topic}}"
    },
    {
     "expr": "avg_over_time(spark_kafkaProcessingLag{job=\"SparkKafkaLagMonitor\", topic=\"alert-events\"}[2m])",
     "legendFormat": "{{consumer}} {{topic}}"
    },
    {
     "expr": "avg_over_time(spark_kafkaProcessingLag{job=\"SparkKafkaLagMonitor\", topic=\"parquet-notif\", consumer!=\"appender\", consumer!=\"derived\", consumer!=\"aggregation-PT1M\", consumer!=\"aggregation-PT15M\", consumer!=\"aggregation-PT1H\", topic!=\"spark_raw_in.f19b6ec7-8bcf-4a95-98e7-dffa97ea16f9.regulator\"}[2m])",
     "legendFormat": "{{consumer}} {{topic}}"
    }
   ]
  },
  {
   "title": "Latent Data",
   "type": "timeseries",
   "description": "Identifies data that is sitting on the latent queue for processing.",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "spark_kafkaProcessingLag{job=\"SparkKafkaLagMonitor\", topic=~\".*latent.*[\\\\.].*\"}",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Spark Ingestion Rate",
   "type": "graph",
   "description": "# Spark ingestion rate\n\nShows the total number of records received from RoadRunner (through Fedex), and the total number of records processed. These two number should be the same overtime on stable systems.\n\nDiscrepancies means that the spark job is getting behind.",
   "gridPos": { "h": 9, "w": 9, "x": 5, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(spark_executor_recordsRead{job=\"spark_streamingapp\"}[10m]))",
     "legendFormat": "totalProcessed"
    },
    {
     "expr": "sum(rate(spark_executor_recordsWritten{job=\"spark_streamingapp\"}[10m]))",
     "legendFormat": "totalReceived"
    }
   ]
  },
  {
   "title": "Kafka Ingestion Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(kafka_server_brokertopicmetrics_oneminuterate{topic=~\"spark_raw_in.*\", name=\"MessagesInPerSec\"}[3m]))",
     "legendFormat": "spark_raw_in MessagesInPerSec"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 16, "x": 5, "y": 48 },
   "options": { "content": "# CPU information" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Overall CPU usage",
   "type": "graph",
   "description": "Since each servers have a different number of CPU...",
   "gridPos": { "h": 9, "w": 8, "x": 5, "y": 50 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)  (irate(node_cpu{mode!=\"idle\"}[5m]))/(count(count(node_cpu) without (mode)) by (instance)) or sum by (instance)  (irate(node_cpu_seconds_total{mode!=\"idle\"}[5m]))/(count(count(node_cpu_seconds_total) without (mode)) by (instance)) ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU I/O Wait",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 13, "y": 50 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (instance) (irate(node_cpu{mode=\"iowait\"}[5m]))/(count(count(node_cpu) without (mode)) by (instance)) or sum by (instance) (irate(node_cpu_seconds_total{mode=\"iowait\"}[5m]))/(count(count(node_cpu_seconds_total) without (mode)) by (instance))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 16, "x": 5, "y": 59 },
   "options": { "content": "# memory and disks" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 5, "y": 61 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "node_memory_Active/node_memory_MemTotal or node_memory_Active_bytes/node_memory_MemTotal_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 13, "y": 61 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1- node_memory_SwapFree/node_memory_SwapTotal or 1- node_memory_SwapFree_bytes/node_memory_SwapTotal_bytes",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "disk usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 5, "y": 69 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(1 - node_filesystem_avail{device !~'tmpfs',device!~'by-uuid'} / node_filesystem_size{device !~'tmpfs',device!~'by-uuid'}) or (1 - node_filesystem_avail_bytes{device !~'tmpfs',device!~'by-uuid'} / node_filesystem_size_bytes{device !~'tmpfs',device!~'by-uuid'})",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "Spark Driver Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 13, "y": 69 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "spark_jvm_total_used/spark_jvm_total_max{job=\"spark_streamingapp\", role=\"driver\"}",
     "legendFormat": "{{spark_AppName}}"
    }
   ]
  },
  {
   "title": "Disk IOPs",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 13, "y": 77 },
   "yaxes": [
    { "format": "short", "label": "Disk Read (+) / Writes (-)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed{}[5m]) * -1 or irate(node_disk_reads_completed_total{}[5m]) * -1",
     "legendFormat": "{{instance}} - {{device}} Reads"
    },
    {
     "expr": "irate(node_disk_writes_completed[5m])",
     "legendFormat": "{{instance}} - {{device}} Writes"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 16, "x": 5, "y": 86 },
   "options": { "content": "# metrics health" },
   "targets": [
    {}
   ]
  },
  {
   "title": "Druid \u0010Status check (/status/health) as reported by each servers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 88 },
   "targets": [
    {
     "expr": "druid_status_gauge{server_type=\"historical\", tier!=\"hot\", result=\"success\"}",
     "legendFormat": "{{server_type}}-{{tier}}-{{result}}"
    },
    {
     "expr": "druid_status_gauge{server_type=\"broker\", result=\"success\"}",
     "legendFormat": "{{server_type}}-{{tier}}-{{result}}"
    },
    {
     "expr": "druid_status_gauge{server_type=\"historical\", tier=\"hot\", result=\"success\"}",
     "legendFormat": "{{server_type}}-{{tier}}-{{result}}"
    },
    {
     "expr": "druid_status_gauge{server_type=\"middle_manager\", result=\"success\"}",
     "legendFormat": "{{server_type}}-{{tier}}-{{result}}"
    },
    {
     "expr": "druid_status_gauge{server_type=\"overlord\", result=\"success\"}",
     "legendFormat": "{{server_type}}-{{tier}}-{{result}}"
    },
    {
     "expr": "druid_status_gauge{server_type=\"peon\", result=\"success\"}",
     "legendFormat": "{{server_type}}-{{tier}}-{{result}}"
    },
    {
     "expr": "druid_status_gauge{server_type=\"coordinator\", result=\"success\"}",
     "legendFormat": "{{server_type}}-{{tier}}-{{result}}"
    }
   ]
  },
  {
   "title": "Druid's overlord view of the cluster, compared to each individual servers (should always be 0)",
   "type": "graph",
   "description": "When this is != 0, it means that either the coordinator / overlord think that some node is connected while it isn't, or some of the nodes think that are connected but coordinator or overlord don't know about it.",
   "gridPos": { "h": 8, "w": 8, "x": 5, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "druid_status_gauge{server_type=\"historical\", tier!=\"hot\", result=\"success\"} - ignoring(result) group_left druid_server_gauge{server_type=\"historical\", tier!=\"hot\"}",
     "legendFormat": "{{server_type}}-{{tier}}"
    },
    {
     "expr": "druid_status_gauge{server_type=\"middle_manager\", result=\"success\"} - ignoring(result) group_left druid_server_gauge{server_type=\"middle_manager\"}",
     "legendFormat": "{{server_type}}"
    },
    {
     "expr": "druid_status_gauge{server_type=\"historical\", tier=\"hot\", result=\"success\"} - ignoring(result) group_left druid_server_gauge{server_type=\"historical\", tier=\"hot\"}",
     "legendFormat": "{{server_type}}-{{tier}}"
    },
    {
     "expr": "druid_status_gauge{server_type=\"broker\", result=\"success\"} - ignoring(result) group_left druid_server_gauge{server_type=\"broker\"}",
     "legendFormat": "{{server_type}}"
    }
   ]
  },
  {
   "title": "Datasource Availability",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 13, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "druid_coordinator_datasourceLoadStatus",
     "legendFormat": "{{datasource}}"
    }
   ]
  },
  {
   "title": "Metrics Service Reachability",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 5, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "metricsService_health_status" }
   ]
  },
  {
   "title": "Bad Segment Date",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 13, "y": 104 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "druid_segment_improperTimestamp",
     "legendFormat": "{{datasource}}"
    }
   ]
  },
  {
   "title": "Query Node Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 5, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "metricsService_datasource_query_nodes"
    }
   ]
  },
  {
   "title": "Ingestion Tasks In Last 24 Hours",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 13, "y": 112 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(druid_ingestion_taskLast24Hour[15m])"
    }
   ]
  },
  {
   "title": "Segments per Interval Distribution",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 5, "y": 120 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "druid_segment_countDistribution",
     "legendFormat": "{{datasource}} {{bucket}}"
    }
   ]
  },
  {
   "title": "Overlord GC Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 14, "y": 120 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(java_lang_GarbageCollector_CollectionCount{job=\"druid-overlord-jmx\", name=\"PS MarkSweep\"}[1h])"
    }
   ]
  },
  {
   "title": "HDFS - Under-Replicated Blocks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 5, "y": 128 },
   "targets": [
    {
     "expr": "hadoop_namenode_under_replicated_blocks{kind=\"FSNamesystem\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HDFS Time Since Last CheckPoint",
   "type": "graph",
   "gridPos": { "h": 8, "w": 17, "x": 5, "y": 137 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(time() - hadoop_namenode_last_checkpoint_time/1000)"
    }
   ]
  }
 ]
}