{
 "title": "RoadRunner",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "Prometheus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "RoadRunner Connection",
   "type": "stat",
   "gridPos": { "h": 11, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(roadrunner_connection{zone!~'test|dummy'}>0) / count(roadrunner_connection{zone!~'test|dummy'})",
     "legendFormat": "{{hostname}}-{{job}}-{{tenant}}"
    }
   ]
  },
  {
   "title": "RoadRunner Connectivity",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 10, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "roadrunner_connection{zone!~'overlord|test|dummy'} ",
     "legendFormat": "{{hostname}} - {{zone}}"
    }
   ]
  },
  {
   "title": "RR-Processing-Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(fedex_record_count{zone!~'overlord|test|dummy'}[5m])) by (hostname,zone)",
     "legendFormat": "{{hostname}} - {{zone}}"
    }
   ]
  }
 ]
}